export const shizenData = {
  1: { // Tuần 1
    1: { // Ngày 1
      title: "Từ láy mô tả hành động & trạng thái 1",
      japanese: "動きと状態を表す言葉 1",
      words: [
        { word: "たまたま", meaning: "thỉnh thoảng, đôi khi, hiếm khi", example: "彼女はたまたまその日は休みをとっていた。" },
        { word: "とうとう", meaning: "cuối cùng, kết cục, sau cùng (cho kết quả tốt)", example: "" },
        { word: "はらはら", meaning: "áy náy, lo lắng, nghẹt thở, thót tim", example: "それは本当にはらはらするような野球の試合だった" },
        { word: "ぼろぼろ", meaning: "rách tơi tả, te tua, rách nát", example: "酷い目にあって身も心もぼろぼろになってしまった" },
        { word: "ぺらぺら／べらべら／ガヤガヤ", meaning: "lưu loát, trôi chảy / bép xép, nói nhiều / ồn ào, ầm ĩ", example: "" },
        { word: "のろのろ", meaning: "chậm rãi, thong thả, ì ạch, chậm như rùa", example: "交通が混雑していたのでのろのろ運転をしなければならなかった." },
        { word: "するする", meaning: "một cách trôi chảy, nhanh chóng, trơn tru スムーズ", example: "サルはするすると木を登っていった" },
        { word: "そわそわ", meaning: "không yên, hoang mang, sốt ruột đi đi lại lại", example: "今日は父さんはそわそわしている." },
        { word: "まずまず", meaning: "kha khá, tàm tạm", example: "彼の仕事はまずまずの出来だが、とても優秀とは言えなかった." },
        { word: "すらすら", meaning: "trơn tru, đọc/nói trôi chảy", example: "彼はその問題をスラスラと解いてしまった." },
        { word: "たびたび", meaning: "thường xuyên, lặp lại nhiều lần", example: "今年はたびたび地震があった. / たびたびお手数を掛けて済みません." },
        { word: "びしょびしょ", meaning: "ướt sũng, sũng nước, ướt đẫm, ướt như chuột lột", example: "" },
        { word: "ぺこぺこ", meaning: "đói meo mốc, đói sôi cả bụng / cúi đầu liên tục", example: "お腹なかがぺこぺこです. 何回も頭を下げる" },
        { word: "ちかちか", meaning: "le lói", example: "" },
        { word: "どきどき", meaning: "hồi hộp, tim đập thình thịch, gay cấn", example: "" },
        { word: "ごろごろ", meaning: "ăn không ngồi rồi, lười nhác / (sấm...) ầm ầm", example: "" },
        { word: "きらきら", meaning: "lấp lánh", example: "星が空にきらきら輝いている." },
        { word: "めちゃめちゃ / めちゃくちゃ", meaning: "lung tung, hỏng tanh bành, tan tành", example: "とても高価な陶器がめちゃめちゃに割れてしまった." },
        { word: "ぽちゃぽちゃ", meaning: "nước bắn tung toé, bì bỡm", example: "" },
        { word: "くらくら", meaning: "hoa mắt, choáng váng, chóng mặt", example: "まだ頭がくらくらした." },
        { word: "ぞろぞろ", meaning: "ùn ùn, nườm nượp, nối đuôi nhau", example: "" }
      ]
    },
    2: { // Ngày 2
      title: "Từ láy mô tả hành động & trạng thái 2",
      japanese: "動きと状態を表す言葉 2",
      words: [
        { word: "たらたら", meaning: "tong tong, tí tách, ròng ròng", example: "" },
        { word: "ひらひら", meaning: "bay bổng, bay phấp phới", example: "" },
        { word: "ずきずき", meaning: "nhức nhối, đau nhức, đau nhoi nhói", example: "" },
        { word: "ずけずけ", meaning: "thẳng thừng, huỵch toẹt", example: "" },
        { word: "おいおい", meaning: "này này / khóc hu hu", example: "" },
        { word: "ずるずる", meaning: "kéo dài mãi, dùng dà dùng dằng không kết thúc được", example: "" },
        { word: "はきはき", meaning: "minh bạch, rõ ràng, sáng suốt, minh mẫn", example: "はきはき返事をする / はきはきしない男だ." },
        { word: "うとうと", meaning: "ngủ gật, ngủ gà ngủ gật", example: "" },
        { word: "ぐいぐい", meaning: "uống (rượu) ừng ực", example: "" },
        { word: "ちびちび", meaning: "nhấm nháp từng ly", example: "" },
        { word: "ぐうぐう", meaning: "ngủ rất sâu, ngủ say, ngủ ngáy", example: "" },
        { word: "くすくす", meaning: "cười tủm tỉm, cười khúc khích", example: "" },
        { word: "げらげら", meaning: "cười ha hả, cười nắc nẻ", example: "" },
        { word: "ぐちゃぐちゃ", meaning: "bừa bộn", example: "" },
        { word: "ぎゅうぎゅう", meaning: "chật ních, chật cứng", example: "" },
        { word: "ぐらぐら", meaning: "lỏng lẻo, xiêu vẹo, rung lắc (động đất, di chuyển)", example: "" },
        { word: "しくしく", meaning: "thút thít, khóc thút thít", example: "" },
        { word: "わんわん", meaning: "khóc òa lên", example: "" },
        { word: "すたすた", meaning: "nhanh nhẹn, đi bộ nhanh nhẹn", example: "" },
        { word: "ばらばら", meaning: "lộn xộn, tan tành, tung tóe", example: "" },
        { word: "ぼさぼさ", meaning: "đầu như tổ quạ", example: "" }
      ]
    },
    3: { // Ngày 3
      title: "Từ láy mô tả trạng thái & mức độ 1",
      japanese: "状態と程度を表す言葉 1",
      words: [
        { word: "ぎりぎり", meaning: "vừa vặn, vừa tới, tới giới hạn, sát sàn sạt", example: "" },
        { word: "ぎらぎら", meaning: "chói chang", example: "夏の太陽がギラギラと我々に照りつけた." },
        { word: "ざあざあ", meaning: "mưa tầm tã, mưa rào, chảy ào ào", example: "雨がざあざあ降っている" },
        { word: "じろじろ", meaning: "nhìn chằm chằm", example: "" },
        { word: "ひそひそ", meaning: "nói thầm thì, lén lút", example: "" },
        { word: "つくづく", meaning: "thật sự, sâu sắc", example: "毎日のきまり仕事にはつくづく飽きた." },
        { word: "そろそろ", meaning: "đã đến lúc, chuẩn bị, sắp sửa", example: "そろそろ戻る時間だ. / そろそろ暗くなってきた." },
        { word: "ところどころ", meaning: "chỗ này chỗ kia", example: "その習慣は今なお日本の所々で行われている." },
        { word: "ちゃくちゃく", meaning: "dần dần từng tí một", example: "仕事は着々進行中だ. / 彼は着々名声を高めていった." },
        { word: "少々", meaning: "một chút, một lúc", example: "" },
        { word: "順々に", meaning: "lần lượt, theo thứ tự", example: "少年たちは順々にしゃべった." },
        { word: "ゆうゆう", meaning: "thong thả, dư sức, có thừa, bình tĩnh, thong dong", example: "悠々とビールを一杯飲んだ. / 電車には悠々と間に合った. / 彼は他の走者を悠々と抜いて行った." },
        { word: "もともと", meaning: "nguyên là, vốn dĩ là, từ đầu", example: "もともと行くつもりはなかった." },
        { word: "めいめい", meaning: "từng người, mỗi người", example: "めいめいその本を 1 冊持っている." },
        { word: "ますます", meaning: "dần dần, ngày càng...", example: "彼女はますます太っていくようだ." },
        { word: "まごまご", meaning: "bối rối, lúng túng", example: "火事と聞いたがまごまごするだけで何一つ出せなかった. / まごまごするな." },
        { word: "まあまあ", meaning: "bình thường, tương đối, khá", example: "昨年の物価上昇 là まあまあだった. / 彼の英語 là まあまあだ." },
        { word: "別々", meaning: "riêng biệt, riêng rẽ", example: "彼らは別々の道を行った. / 勘定は別々にして下さい." },
        { word: "ふわふわ", meaning: "mềm và mượt, bồng bềnh", example: "ふわふわした猫だ" },
        { word: "ぶつぶつ", meaning: "làu bàu, nói đi nói lại", example: "いつまでもぶつぶつ言うな." },
        { word: "ひろびろ", meaning: "rộng rãi", example: "広々とした庭" }
      ]
    },
    4: { // Ngày 4
      title: "Từ láy mô tả trạng thái & mức độ 2",
      japanese: "状態と程度を表す言葉 2",
      words: [
        { word: "ぴかぴか", meaning: "lấp lánh, sáng loáng, óng ánh", example: "靴をブラシでぴかぴかに磨く / 星がぴかぴか光っている." },
        { word: "こそこそ", meaning: "nhẹ nhàng, lén lút", example: "こそこそ立ち去る / こそこそせずに堂々と批判して欲しい." },
        { word: "にこにこ", meaning: "mỉm cười, tủm tỉm", example: "彼はにこにこ顔だった." },
        { word: "中々 (なかなか)", meaning: "mãi mà không..., rất, cực kỳ", example: "なかなか容易でない / 彼はなかなかの外交家だ." },
        { word: "ちかぢか", meaning: "gần sắp, cận kề", example: "近々に出発の予定です." },
        { word: "だんだん", meaning: "dần dần", example: "彼女はだんだん体調がよくなっています." },
        { word: "でこぼこ", meaning: "lồi lõm", example: "でこぼこ道" },
        { word: "それぞれ", meaning: "từng cái từng cái một", example: "各人それぞれの理想がある. / 物にはそれぞれ取り柄がある." },
        { word: "じょじょに", meaning: "dần dần, từng chút một", example: "騒音は徐々に減少した." },
        { word: "かたがた", meaning: "người này người kia", example: "わからなかったら方々の人に聞いた方がいいよ" },
        { word: "おのおの", meaning: "từng người, mỗi cái", example: "人には各々長所 và 短所とがある. / おのおのの建物のは名前がある." },
        { word: "つぎつぎ", meaning: "liên tiếp hết cái này đến cái khác", example: "最近交通事故がしきりに起きる. / 誰かがしきりに門を叩いている." },
        { word: "いらいら", meaning: "tức tối, nóng nảy, bực bội", example: "彼は気がいらいらしていた. / 彼女の来るのが遅いので彼はいらいらしていた." },
        { word: "いちいち", meaning: "lần lượt từng cái một", example: "おっしゃることはいちいちごもっともです / 彼は私のしたことにいちいち文句を言う." },
        { word: "生き生き", meaning: "sống động, tươi sống, đầy sức sống", example: "彼は生き生きとした想像力を持っている." },
        { word: "いよいよ", meaning: "ngày càng, cuối cùng", example: "雨はやむどころかいよいよひどくなった. / いよいよ千載一遇のチャンスがめぐってきた." },
        { word: "あちこち", meaning: "đây đó, khắp nơi khắp chốn", example: "" },
        { word: "むかむか", meaning: "nôn nao, buồn nôn", example: "" },
        { word: "うんざり", meaning: "chán ngấy đến tận cổ", example: "" },
        { word: "うっとり", meaning: "say sưa (nhìn, nghe...)", example: "" },
        { word: "わくわく", meaning: "hào hứng", example: "" }
      ]
    },
    5: { // Ngày 5
      title: "Từ láy mô tả cảm xúc & cảm giác 1",
      japanese: "感情と感覚を表す言葉 1",
      words: [
        { word: "ぞくぞく", meaning: "run như cầy sấy", example: "" },
        { word: "うきうき", meaning: "mừng rỡ", example: "" },
        { word: "いそいそ", meaning: "hớn hở", example: "" },
        { word: "おどおど", meaning: "run rẩy thiếu tự tin", example: "" },
        { word: "びくびく", meaning: "lo lắng sợ sệt", example: "" },
        { word: "おろおろ", meaning: "bối rối vô cùng", example: "" },
        { word: "くよくよ", meaning: "day dứt mãi", example: "" },
        { word: "もじもじ", meaning: "nói lắp bắp vì ngượng", example: "" },
        { word: "しょんぼり", meaning: "buồn thỉu buồn thiu", example: "" },
        { word: "ぼんやり", meaning: "lơ đễnh", example: "" },
        { word: "けろりと", meaning: "tảng lờ, phớt lờ", example: "" },
        { word: "ぴんぴん", meaning: "(tuổi già) sung sức", example: "" },
        { word: "だらだら", meaning: "uể oải, chậm rãi", example: "" },
        { word: "ぐずぐず", meaning: "do dự, đắn đo", example: "" },
        { word: "うろうろ", meaning: "đi tha thẩn", example: "" },
        { word: "よろよろ", meaning: "loạng choạng", example: "" },
        { word: "からから", meaning: "khát khô cả họng", example: "" },
        { word: "ふらふら", meaning: "say xẩm mặt mày, chóng mặt", example: "" },
        { word: "がんがん", meaning: "(đầu) đau như búa bổ", example: "" },
        { word: "ちくちく", meaning: "đau như kim chích", example: "" },
        { word: "ひりひり", meaning: "bỏng rát", example: "" }
      ]
    },
    6: { // Ngày 6
      title: "Từ láy mô tả âm thanh & hành động nhanh",
      japanese: "音と素早い動きを表す言葉",
      words: [
        { word: "ぶうぶう", meaning: "(nói) bất mãn, lẩm bẩm", example: "" },
        { word: "ぐるぐる", meaning: "(chạy, quay) vù vù", example: "" },
        { word: "ぶるぶる", meaning: "(run) như lẩy bẩy", example: "" },
        { word: "さっさと", meaning: "ngay lập tức", example: "" },
        { word: "せっせと", meaning: "miệt mài, chăm chỉ", example: "" },
        { word: "てきぱき", meaning: "nhanh gọn hiệu quả", example: "" },
        { word: "きっぱり", meaning: "dứt khoát, nhất quyết (nghỉ việc, từ chối...)", example: "" },
        { word: "どんどん", meaning: "nhiều vào", example: "" },
        { word: "ぐんぐん", meaning: "vù vù, vèo một cái", example: "" },
        { word: "めきめき", meaning: "(lớn) nhanh như thổi", example: "" },
        { word: "ぼつぼつ", meaning: "bắt đầu dần dần", example: "" },
        { word: "にやにや", meaning: "cười đểu, cười mỉa mai", example: "" },
        { word: "すやすや", meaning: "ngủ ngoan hiền", example: "" },
        { word: "がたがた", meaning: "lách cách, lạch cạch", example: "" },
        { word: "ゆらゆら", meaning: "rung rinh, lay động", example: "" },
        { word: "ちょろちょろ", meaning: "(chảy) tồ tồ", example: "" },
        { word: "ぽろぽろ", meaning: "(chảy) giàn giụa", example: "" },
        { word: "ぱらぱら", meaning: "(rơi) tí tách", example: "" },
        { word: "ぽきぽき", meaning: "(kêu) răng rắc", example: "" },
        { word: "びりびり", meaning: "xé toạc", example: "" },
        { word: "ぶくぶく", meaning: "(béo) ú, (sôi, sủi bọt) lốp bốp", example: "" }
      ]
    },
    7: { // Ngày 7
      title: "Từ láy mô tả tính chất & bề mặt",
      japanese: "性質と表面を表す言葉",
      words: [
        { word: "ごちゃごちゃ", meaning: "lung tung, bừa bộn", example: "" },
        { word: "くしゃくしゃ", meaning: "nhàu nhĩ", example: "" },
        { word: "こちこち", meaning: "khô quắt, khô khan", example: "" },
        { word: "かさかさ", meaning: "khô cứng", example: "" },
        { word: "あっさり", meaning: "hời hợt, nhạt (thức ăn)", example: "" },
        { word: "こってり", meaning: "sặc mùi, đậm mùi", example: "" },
        { word: "だぶだぶ", meaning: "thùng thình", example: "" },
        { word: "すれすれ", meaning: "gần như", example: "" },
        { word: "どっしり", meaning: "cồng kềnh", example: "" },
        { word: "ぎっしり", meaning: "chật như nêm", example: "" },
        { word: "うんと", meaning: "nhiều (tiền...)", example: "" },
        { word: "ぐにゃぐにゃ", meaning: "uốn lượn", example: "" },
        { word: "ねばねば", meaning: "dính", example: "" },
        { word: "じめじめ", meaning: "nhớp nháp", example: "" },
        { word: "むんむん", meaning: "đông nghẹt", example: "" },
        { word: "ざらざら", meaning: "ram ráp", example: "" },
        { word: "つるつる", meaning: "trơn trơn bóng", example: "" },
        { word: "ぴりっと", meaning: "rất cay, nóng nảy", example: "" },
        { word: "ぬるぬる", meaning: "trơn tuồn tuột", example: "" },
        { word: "べたべた", meaning: "dính nhơm nhớp", example: "" }
      ]
    }
  }
};
