import { kanjiComprehensiveData } from './data/kanjiComprehensiveData';

export const examVocabData = {
  "comprehensive": {
    title: "Từ vựng tổng hợp PC7",
    japanese: "総合語彙 - PC7対策",
    words: [
      { kanji: "体育", kana: "たいいく", meaning: "thể dục" },
      { kanji: "大陸", kana: "たいりく", meaning: "lục địa" },
      { kanji: "急ぐ", kana: "いそぐ", meaning: "vội vàng, gấp gáp" },
      { kanji: "行う", kana: "おこなう", meaning: "tổ chức, thực hiện" },
      { kanji: "天気予報", kana: "てんきよほう", meaning: "dự báo thời tiết" },
      { kanji: "暖める / 温める", kana: "あたためる", meaning: "làm ấm / làm nóng" },
      { kanji: "電源", kana: "でんげん", meaning: "nguồn điện" },
      { kanji: "日当たり", kana: "ひあたり", meaning: "nơi có ánh nắng chiếu" },
      { kanji: "蛇口", kana: "じゃぐち", meaning: "vòi nước" },
      { kanji: "天井", kana: "てんじょう", meaning: "trần nhà" },
      { kanji: "模様", kana: "もよう", meaning: "hoa văn, họa tiết" },
      { kanji: "流行", kana: "りゅうこう", meaning: "thịnh hành, xu hướng" },
      { kanji: "品物", kana: "しなもの", meaning: "hàng hóa" },
      { kanji: "指輪", kana: "ゆびわ", meaning: "nhẫn, chiếc nhẫn" },
      { kanji: "無料", kana: "むりょう", meaning: "miễn phí" },
      { kanji: "迷惑", kana: "めいわく", meaning: "phiền hà, quấy rầy" },
      { kanji: "交流", kana: "こうりゅう", meaning: "giao lưu" },
      { kanji: "暴れる", kana: "あばれる", meaning: "quậy phá, rầm rĩ" },
      { kanji: "騒ぐ", kana: "さわぐ", meaning: "làm ồn" },
      { kanji: "放題", kana: "ほうだい", meaning: "thỏa thích, hết mình" },
      { kanji: "乾杯", kana: "かんぱい", meaning: "cạn chén, nâng ly" },
      { kanji: "節約", kana: "せつやく", meaning: "tiết kiệm" },
      { kanji: "合計", kana: "ごうけい", meaning: "tổng cộng" },
      { kanji: "履歴書", kana: "りれきしょう", meaning: "sơ yếu lý lịch, CV" },
      { kanji: "夫婦", kana: "ふうふ", meaning: "Vợ chồng" },
      { kanji: "怖い", kana: "こわい", meaning: "Sợ hãi" },
      { kanji: "悩む", kana: "なやむ", meaning: "Phiền não, trăn trở" },
      { kanji: "休日", kana: "きゅうじつ", meaning: "Ngày nghỉ" },
      { kanji: "行動", kana: "こうどう", meaning: "Hành động" },
      { kanji: "決定", kana: "けってい", meaning: "Quyết định" },
      { kanji: "調査", kana: "ちょうさ", meaning: "Điều tra" },
      { kanji: "近所", kana: "きんじょ", meaning: "Hàng xóm, lân cận" },
      { kanji: "お正月", kana: "おしょうがつ", meaning: "Tết" },
      { kanji: "狭い", kana: "せまい", meaning: "Chật hẹp" },
      { kanji: "一生", kana: "いっしょう", meaning: "Cả đời, một đời" },
      { kanji: "一緒", kana: "いっしょ", meaning: "Cùng nhau" },
      { kanji: "手術", kana: "しゅじゅつ", meaning: "Phẫu thuật" },
      { kanji: "液体", kana: "えきたい", meaning: "Chất lỏng" },
      { kanji: "無事", kana: "ぶじ", meaning: "Bình an, vô sự" },
      { kanji: "満足", kana: "まんぞく", meaning: "Thỏa mãn, hài lòng" },
      { kanji: "記録", kana: "きろく", meaning: "Kỷ lục, ghi chép" },
      { kanji: "仲介料", kana: "ちゅうかいりょう", meaning: "Phí môi giới" },
      { kanji: "大切", kana: "たいせつ", meaning: "Quan trọng" },
      { kanji: "落ちる", kana: "おちる", meaning: "Rơi, rớt" },
      { kanji: "花粉", kana: "かふん", meaning: "Phấn hoa" },
      { kanji: "商店", kana: "しょうてん", meaning: "Cửa hàng" },
      { kanji: "留守番", kana: "るすばん", meaning: "Trông nhà" },
      { kanji: "範囲", kana: "はんい", meaning: "Phạm vi" },
      { kanji: "結論", kana: "けつろん", meaning: "Kết luận" },
      { kanji: "燃える", kana: "もえる", meaning: "Cháy" },
      { kanji: "大量", kana: "たいりょう", meaning: "Số lượng lớn" },
      { kanji: "願書", kana: "がんしょ", meaning: "Đơn đăng ký, đơn xin nhập học" },
      { kanji: "設立", kana: "せつりつ", meaning: "Thành lập" },
      { kanji: "保存", kana: "ほぞん", meaning: "Bảo tồn, lưu trữ" },
      { kanji: "存在", kana: "そんざい", meaning: "Tồn tại" },
      { kanji: "祝福", kana: "しゅくふく", meaning: "Chúc phúc" },
      { kanji: "環境", kana: "かんきょう", meaning: "Môi trường" },
      { kanji: "頭痛", kana: "ずつう", meaning: "Đau đầu" },
      { kanji: "建築", kana: "けんちく", meaning: "Kiến trúc" },
      { kanji: "探検", kana: "たんけん", meaning: "Thám hiểm" },
      { kanji: "相談", kana: "そうだんする", meaning: "Thảo luận, bàn bạc" },
      { kanji: "身近", kana: "みぢかな", meaning: "Gần gũi, quen thuộc" },
      { kanji: "笑顔", kana: "えがお", meaning: "Khuôn mặt tươi cười" },
      { kanji: "守衛", kana: "しゅえい", meaning: "Nhân viên bảo vệ" },
      { kanji: "救う", kana: "すくう", meaning: "Cứu giúp" },
      { kanji: "熱湯", kana: "ねっとう", meaning: "Nước sôi" },
      { kanji: "感想 / 乾燥", kana: "かんそう", meaning: "Cảm tưởng / Khô ráo" },
      { kanji: "初雪", kana: "はつゆき", meaning: "Tuyết đầu mùa" },
      { kanji: "悲観", kana: "ひかん", meaning: "Bi quan" },
      { kanji: "勝負", kana: "しょうぶ", meaning: "Thắng thua, trận đấu" },
      { kanji: "行列", kana: "ぎょうれつ", meaning: "Hàng người, xếp hàng" }
    ]
  },
  "kanji-comprehensive": {
    title: "Hán tự tổng hợp PC7",
    japanese: "漢字総合 - PC7対策",
    words: kanjiComprehensiveData
  }
};
