export const soumatomeData = {
  1: { // Tuần 1
    1: { // Ngày 1
      title: "Nhà bếp – phòng khách",
      japanese: "キッチンで / リビングで",
      words: [
        { kanji: "台所", kana: "だいどころ", meaning: "nhà bếp" },
        { kanji: "電子レンジ", kana: "でんしれんじ", meaning: "lò vi sóng" },
        { kanji: "お茶わん", kana: "おちゃわん", meaning: "chén" },
        { kanji: "ワイングラス", kana: "ワイングラス", meaning: "ly uống rượu" },
        { kanji: "コーヒーカップ", kana: "コーヒーカップ", meaning: "tách cà phê" },
        { kanji: "茶わん", kana: "ちゃわん", meaning: "ly, cốc uống trà" },
        { kanji: "湯飲み", kana: "ゆのみ", meaning: "tách trà" },
        { kanji: "ガスレンジ", kana: "ガスレンジ", meaning: "bếp ga" },
        { kanji: "ガスコンロ", kana: "ガスコンロ", meaning: "bếp ga di động, bếp gas" },
        { kanji: "ガラスのコップ", kana: "ガラスのコップ", meaning: "ly thủy tinh" },
        { kanji: "レバー", kana: "レバー", meaning: "cần gạt số, cần điều khiển" },
        { kanji: "流し", kana: "ながし", meaning: "bồn, chậu rửa" },
        { kanji: "居間", kana: "いま", meaning: "phòng khách" },
        { kanji: "リビング", kana: "リビング", meaning: "phòng khách" },
        { kanji: "窓ガラス", kana: "まどガラス", meaning: "cửa kính; kính cửa sổ" },
        { kanji: "雨戸", amado: "あまど", meaning: "cửa sập, cửa che mưa, cửa chớp" },
        { kanji: "網戸", kana: "あみど", meaning: "cửa lưới" },
        { kanji: "天井", kana: "てんじょう", meaning: "trần nhà" },
        { kanji: "床", kana: "ゆか", meaning: "sàn nhà" },
        { kanji: "コンセント", kana: "コンセント", meaning: "ổ cắm điện" },
        { kanji: "コード", kana: "コード", meaning: "dây dẫn" },
        { kanji: "エアコン", kana: "エアコン", meaning: "máy điều hòa" },
        { kanji: "ヒーター", kana: "ヒーター", meaning: "máy sưởi, lò sưởi" },
        { kanji: "カーペット", kana: "カーペット", meaning: "tấm thảm" },
        { kanji: "蛇口", kana: "じゃぐち", meaning: "vòi nước" },
        { kanji: "水道の蛇口をひねる", kana: "すいどうのじゃぐちをひねる", meaning: "mở vòi nước" },
        { kanji: "水が凍る", kana: "みずがこおる", meaning: "nước đông lạnh" },
        { kanji: "氷になる", kana: "こおりになる", meaning: "nước đá, thành nước đá" },
        { kanji: "冷凍して保存する", kana: "れいとうしてほぞんする", meaning: "làm lạnh, làm đông sau đó đem bảo quản" },
        { kanji: "残り物を温める", kana: "のこりものをあたためる", meaning: "làm nóng đồ ăn thừa" },
        { kanji: "ビールを冷やす", kana: "ビールをひやす", meaning: "làm lạnh bia" },
        { kanji: "ビールが冷えている", kana: "ビールがひえている", meaning: "bia được làm lạnh" },
        { kanji: "エアコンのリモコン", kana: "エアコンのリモコン", meaning: "điều khiển điều hòa" },
        { kanji: "スイッチ", kana: "スイッチ", meaning: "công tắc" },
        { kanji: "電源を入れる", kana: "でんげんをいれる", meaning: "mở điện, bật nguồn điện" },
        { kanji: "電源を切る", kana: "でんげんをきる", meaning: "tắt điện, cắt nguồn điện" },
        { kanji: "じゅうたんを敷く", kana: "じゅうたんをしく", meaning: "trải thảm" },
        { kanji: "暖房をつける", kana: "だんぼうをつける", meaning: "bật lò sưởi" },
        { kanji: "冷房が効いている", kana: "れいぼうがきいている", meaning: "máy lạnh đang hoạt động" },
        { kanji: "日当たりがいい", kana: "ひあたりがいい", meaning: "có ánh nắng chiều vào" },
        { kanji: "日当たりが悪い", kana: "ひあたりがわるい", meaning: "không có ánh nắng chiều vào" },
      ]
    }
  }
};
