export const week6Data = {
  6: {
    1: {
      title: "Phó từ chỉ thời gian, kết quả, mức độ",
      japanese: "時・結果・程度の副詞",
      words: [
        { kanji: "突然", kana: "とつぜん", meaning: "Đột nhiên, bất ngờ" },
        { kanji: "いきなり", kana: "いきなり", meaning: "Đột nhiên, bất ngờ" },
        { kanji: "とたんに", kana: "とたんに", meaning: "Bỗng nhiên, ngay khi" },
        { kanji: "やっと", kana: "やっと", meaning: "Rốt cuộc, cuối cùng thì (kết quả tốt)" },
        { kanji: "とうとう", kana: "とうとう", meaning: "Cuối cùng thì, sau cùng" },
        { kanji: "結局", kana: "けっきょく", meaning: "Kết cục, rốt cuộc" },
        { kanji: "ついに", kana: "ついに", meaning: "Cuối cùng thì" },
        { kanji: "よく", kana: "よく", meaning: "Thường hay / Giỏi, tốt" },
        { kanji: "たいてい", kana: "たいてい", meaning: "Thường thường, phần lớn" },
        { kanji: "ふだん", kana: "ふだん", meaning: "Thường thì, bình thường" },
        { kanji: "ふつう", kana: "ふつう", meaning: "Thông thường" },
        { kanji: "たまに", kana: "たまに", meaning: "Thỉnh thoảng, hiếm khi" },
        { kanji: "かなり", kana: "かなり", meaning: "Khá là, tương đối" },
        { kanji: "けっこう", kana: "けっこう", meaning: "Khá, tương đối / Đủ rồi" },
        { kanji: "ものすごく", kana: "ものすごく", meaning: "Cực kì, quá xá" },
        { kanji: "めちゃくちゃ", kana: "めちゃくちゃ", meaning: "Lộn xộn, tan tành / Cực kỳ" },
        { kanji: "むちゃくちゃ", kana: "むちゃくちゃ", meaning: "Lộn xộn / Rất, cực kỳ" },
        { kanji: "ぜひ", kana: "ぜひ", meaning: "Nhất định (mong muốn)" },
        { kanji: "ぜひとも", kana: "ぜひとも", meaning: "Thế nào cũng, nhất định" },
        { kanji: "どうか", kana: "どうか", meaning: "Xin (nhờ vả)" },
        { kanji: "まず", kana: "まず", meaning: "Đầu tiên, trước hết" },
        { kanji: "とにかく", kana: "とにかく", meaning: "Dù sao đi nữa, trước mắt" },
        { kanji: "ともかく", kana: "ともかく", meaning: "Dù sao đi nữa" },
        { kanji: "一度に", kana: "いちどに", meaning: "Cùng một lúc" },
        { kanji: "いっぺんに", kana: "いっぺんに", meaning: "Cùng một lúc, ngay lập tức" },
        { kanji: "だいたい", kana: "だいたい", meaning: "Đại khái, khoảng" },
        { kanji: "非常に", kana: "ひじょうに", meaning: "Rất, cực kỳ" },
        { kanji: "絶対に", kana: "ぜったいに", meaning: "Tuyệt đối" },
        { kanji: "全く", kana: "まったく", meaning: "Hoàn toàn (thường đi với phủ định)" },
        { kanji: "少しも", kana: "すこしも", meaning: "Một chút cũng không" }
      ]
    },
    2: {
      title: "Từ vựng nhấn mạnh, trạng thái",
      japanese: "強調・様子の副詞",
      words: [
        { kanji: "うっかり", kana: "うっかり", meaning: "Lơ đãng, vô ý" },
        { kanji: "すっかり", kana: "すっかり", meaning: "Hoàn toàn, toàn bộ" },
        { kanji: "がっかり", kana: "がっかり", meaning: "Thất vọng" },
        { kanji: "やっぱり", kana: "やっぱり", meaning: "Quả nhiên, vẫn (như dự đoán)" },
        { kanji: "やはり", kana: "やはり", meaning: "Quả nhiên, vẫn (lịch sự hơn)" },
        { kanji: "しっかり", kana: "しっかり", meaning: "Chắc chắn, vững vàng, đáng tin cậy" },
        { kanji: "すっきり", kana: "すっきり", meaning: "Sảng khoái, rõ ràng, gọn gàng" },
        { kanji: "さっぱり", kana: "さっぱり", meaning: "Sảng khoái / Hoàn toàn không" },
        { kanji: "ぐっすり", kana: "ぐっすり", meaning: "Ngủ say, ngủ ngon" },
        { kanji: "にっこり", kana: "にっこり", meaning: "Cười mỉm" },
        { kanji: "にこにこ", kana: "にこにこ", meaning: "Cười tủm tỉm, tươi cười" },
        { kanji: "そっくり", kana: "そっくり", meaning: "Giống y hệt" },
        { kanji: "はっきり", kana: "はっきり", meaning: "Rõ ràng" },
        { kanji: "のんびり", kana: "のんびり", meaning: "Thong thả, thong dong" },
        { kanji: "きちんと", kana: "きちんと", meaning: "Cẩn thận, chỉn chu, ngăn nắp" },
        { kanji: "ちゃんと", kana: "ちゃんと", meaning: "Đàng hoàng, nghiêm chỉnh" },
        { kanji: "ふと", kana: "ふと", meaning: "Đột nhiên, chợt (nghĩ ra, nhìn thấy)" },
        { kanji: "わざと", kana: "わざと", meaning: "Cố tình, cố ý" },
        { kanji: "ほっと", kana: "ほっと", meaning: "Yên tâm, nhẹ nhõm" },
        { kanji: "じっと", kana: "じっと", meaning: "Chịu đựng / Nhìn chằm chằm / Không nhúc nhích" },
        { kanji: "ざっと", kana: "ざっと", meaning: "Lướt qua, qua loa, đại khái" },
        { kanji: "そっと", kana: "そっと", meaning: "Lặng lẽ, rón rén" },
        { kanji: "なるべく", kana: "なるべく", meaning: "Càng... càng tốt, nếu có thể" },
        { kanji: "ちっとも", kana: "ちっとも", meaning: "Một chút cũng không" },
        { kanji: "めったに", kana: "めったに", meaning: "Hiếm khi (đi với phủ định)" }
      ]
    },
    3: {
      title: "Từ tượng thanh, tượng hình",
      japanese: "オノマトペ（状態・感情）",
      words: [
        { kanji: "どきどき", kana: "どきどき", meaning: "Hồi hộp, tim đập thình thịch" },
        { kanji: "いらいら", kana: "いらいら", meaning: "Sốt ruột, bồn chồn, bực bội" },
        { kanji: "はきはき", kana: "はきはき", meaning: "Rõ ràng, lanh lợi (nói năng)" },
        { kanji: "ぶつぶつ", kana: "ぶつぶつ", meaning: "Lầm bầm, cằn nhằn / Nổi mụn" },
        { kanji: "うろうろ", kana: "うろうろ", meaning: "Đi loanh quanh, lảng vảng" },
        { kanji: "ぶらぶら", kana: "ぶらぶら", meaning: "Đi lang thang, đung đưa" },
        { kanji: "ぎりぎり", kana: "ぎりぎり", meaning: "Sát nút, vừa kịp, giới hạn" },
        { kanji: "ぴかぴか", kana: "ぴかぴか", meaning: "Sáng bóng, lấp lánh" },
        { kanji: "のろのろ", kana: "のろのろ", meaning: "Chậm chạp, lề mề" },
        { kanji: "ぺらぺら", kana: "ぺらぺら", meaning: "Nói lưu loát / Mỏng dính (vải, giấy)" },
        { kanji: "ぺこぺこ", kana: "ぺこぺこ", meaning: "Đói meo, đói cồn cào / Khúm núm" },
        { kanji: "ますます", kana: "ますます", meaning: "Ngày càng" },
        { kanji: "だんだん", kana: "だんだん", meaning: "Dần dần" },
        { kanji: "どんどん", kana: "どんどん", meaning: "Nhanh chóng, vùn vụt, dồn dập" },
        { kanji: "からから", kana: "からから", meaning: "Khô khốc, khát khô" },
        { kanji: "ぼろぼろ", kana: "ぼろぼろ", meaning: "Rách tơi tả, rã rời" },
        { kanji: "わくわく", kana: "わくわく", meaning: "Háo hức, phấn khởi" },
        { kanji: "ばらばら", kana: "ばらばら", meaning: "Rời rạc, lộn xộn, tản mác" },
        { kanji: "こっそり", kana: "こっそり", meaning: "Lén lút, vụng trộm" },
        { kanji: "ぴったり", kana: "ぴったり", meaning: "Vừa vặn, vừa khít" },
        { kanji: "ぎっしり", kana: "ぎっしり", meaning: "Chật ních, kín mít" },
        { kanji: "ゆっくり", kana: "ゆっくり", meaning: "Từ từ, chậm rãi" }
      ]
    },
    4: {
      title: "Từ vựng Katakana 1",
      japanese: "カタカナ語①",
      words: [
        { kanji: "アイデア", kana: "アイデア", meaning: "Ý tưởng" },
        { kanji: "メッセージ", kana: "メッセージ", meaning: "Tin nhắn, thông điệp" },
        { kanji: "ルール", kana: "ルール", meaning: "Quy tắc, luật lệ" },
        { kanji: "マナー", kana: "マナー", meaning: "Quy tắc ứng xử, văn hóa" },
        { kanji: "ミス", kana: "ミス", meaning: "Lỗi lầm, sai sót" },
        { kanji: "スケジュール", kana: "スケジュール", meaning: "Lịch trình, thời khóa biểu" },
        { kanji: "アンケート", kana: "アンケート", meaning: "Bảng khảo sát, phiếu điều tra" },
        { kanji: "インタビュー", kana: "インタビュー", meaning: "Phỏng vấn" },
        { kanji: "アドバイス",アドバイス: "アドバイス", meaning: "Lời khuyên" },
        { kanji: "リサイクル", kana: "リサイクル", meaning: "Tái chế" },
        { kanji: "エコ", kana: "エコ", meaning: "Bảo vệ môi trường, sinh thái" },
        { kanji: "ボランティア", kana: "ボランティア", meaning: "Tình nguyện viên" },
        { kanji: "ストレス", kana: "ストレス", meaning: "Căng thẳng" },
        { kanji: "ダイエット", kana: "ダイエット", meaning: "Ăn kiêng, giảm cân" },
        { kanji: "カロリー", kana: "カロリー", meaning: "Năng lượng (calorie)" },
        { kanji: "トラブル", kana: "トラブル", meaning: "Rắc rối, sự cố" },
        { kanji: "ベテラン", kana: "ベテラン", meaning: "Người có kinh nghiệm, lão luyện" },
        { kanji: "プロ", kana: "プロ", meaning: "Chuyên nghiệp" },
        { kanji: "アマチュア", kana: "アマチュア", meaning: "Nghiệp dư" },
        { kanji: "リーダー", kana: "リーダー", meaning: "Trưởng nhóm, lãnh đạo" }
      ]
    },
    5: {
      title: "Từ vựng Katakana 2",
      japanese: "カタカナ語②",
      words: [
        { kanji: "システム", kana: "システム", meaning: "Hệ thống" },
        { kanji: "データ", kana: "データ", meaning: "Dữ liệu" },
        { kanji: "デザイン", kana: "デザイン", meaning: "Thiết kế" },
        { kanji: "スタイル", kana: "スタイル", meaning: "Phong cách, kiểu dáng" },
        { kanji: "サイズ", kana: "サイズ", meaning: "Kích cỡ" },
        { kanji: "パターン", kana: "パターン", meaning: "Kiểu mẫu, hoa văn" },
        { kanji: "マーク", kana: "マーク", meaning: "Dấu hiệu, ký hiệu" },
        { kanji: "イラスト", kana: "イラスト", meaning: "Hình minh họa" },
        { kanji: "サイン", kana: "サイン", meaning: "Chữ ký, ký tên" },
        { kanji: "メモ", kana: "メモ", meaning: "Ghi chú" },
        { kanji: "タイトル", kana: "タイトル", meaning: "Tiêu đề" },
        { kanji: "テーマ", kana: "テーマ", meaning: "Chủ đề" },
        { kanji: "ストーリー", kana: "ストーリー", meaning: "Câu chuyện" },
        { kanji: "ヒット", kana: "ヒット", meaning: "Thành công, nổi tiếng, đánh trúng" },
        { kanji: "ブランド", kana: "ブランド", meaning: "Hàng hiệu, thương hiệu" },
        { kanji: "レンタル", kana: "レンタル", meaning: "Thuê, cho thuê" },
        { kanji: "フリー", kana: "フリー", meaning: "Miễn phí, tự do" },
        { kanji: "パーセント", kana: "パーセント", meaning: "Phần trăm" },
        { kanji: "チャンス", kana: "チャンス", meaning: "Cơ hội" },
        { kanji: "タイミング", kana: "タイミング", meaning: "Thời điểm" },
        { kanji: "ペース", kana: "ペース", meaning: "Nhịp độ, tốc độ" }
      ]
    },
    6: {
      title: "Tổng hợp các loại từ",
      japanese: "まとめの語彙",
      words: [
        { kanji: "そろそろ", kana: "そろそろ", meaning: "Sắp sửa, chuẩn bị" },
        { kanji: "もともと", kana: "もともと", meaning: "Vốn dĩ, từ đầu" },
        { kanji: "たまたま", kana: "たまたま", meaning: "Tình cờ, ngẫu nhiên" },
        { kanji: "まあまあ", kana: "まあまあ", meaning: "Tàm tạm, bình thường" },
        { kanji: "さまざま", kana: "さまざま", meaning: "Nhiều loại, đa dạng" },
        { kanji: "なるほど", kana: "なるほど", meaning: "Thảo nào, thì ra là thế" },
        { kanji: "やっぱり", kana: "やっぱり", meaning: "Quả nhiên là" },
        { kanji: "おそらく", kana: "おそらく", meaning: "Có lẽ, e rằng" },
        { kanji: "たしか", kana: "たしか", meaning: "Chắc là, nhớ không nhầm thì" },
        { kanji: "たしかに", kana: "たしかに", meaning: "Chính xác là, chắc chắn là" },
        { kanji: "万一", kana: "まんいち", meaning: "Lỡ như, vạn nhất" },
        { kanji: "たとえ", kana: "たとえ", meaning: "Cho dù (có thế nào đi nữa)" },
        { kanji: "ちょうど", kana: "ちょうど", meaning: "Vừa đúng, y như" },
        { kanji: "まるで", kana: "まるで", meaning: "Hoàn toàn (như là...)" },
        { kanji: "いつの間にか", kana: "いつのまにか", meaning: "Từ lúc nào không hay" },
        { kanji: "あっという間に", kana: "あっというまに", meaning: "Trong nháy mắt" },
        { kanji: "いつか", kana: "いつか", meaning: "Lúc nào đó, ngày nào đó" },
        { kanji: "いつでも", kana: "いつでも", meaning: "Bất cứ lúc nào" },
        { kanji: "どこか", kana: "どこか", meaning: "Đâu đó" },
        { kanji: "どこでも", kana: "どこでも", meaning: "Bất cứ đâu" },
        { kanji: "だれか", kana: "だれか", meaning: "Ai đó" },
        { kanji: "だれでも", kana: "だれでも", meaning: "Bất cứ ai" }
      ]
    }
  }
};
