export const week4Data = {
  4: {
    1: {
      title: "Tin tức, Báo chí",
      japanese: "ニュース・新聞",
      words: [
        { kanji: "記事", kana: "きじ", meaning: "Bài báo, phóng sự" },
        { kanji: "見出し", kana: "みだし", meaning: "Tiêu đề" },
        { kanji: "事件", kana: "じけん", meaning: "Vụ án, sự kiện" },
        { kanji: "事故", kana: "じこ", meaning: "Tai nạn" },
        { kanji: "警察", kana: "けいさつ", meaning: "Cảnh sát" },
        { kanji: "犯人", kana: "はんにん", meaning: "Thủ phạm, tội phạm" },
        { kanji: "逮捕する", kana: "たいほする", meaning: "Bắt giữ" },
        { kanji: "捕まる", kana: "つかまる", meaning: "Bị bắt" },
        { kanji: "盗む", kana: "ぬすむ", meaning: "Ăn cắp" },
        { kanji: "泥棒", kana: "どろぼう", meaning: "Kẻ trộm" },
        { kanji: "交通事故", kana: "こうつうじこ", meaning: "Tai nạn giao thông" },
        { kanji: "衝突する", kana: "しょうとつする", meaning: "Va chạm, đụng nhau" },
        { kanji: "被害", kana: "ひがい", meaning: "Thiệt hại" },
        { kanji: "被害者", kana: "ひがいしゃ", meaning: "Người bị hại, nạn nhân" },
        { kanji: "伝える", kana: "つたえる", meaning: "Truyền đạt, đưa tin" },
        { kanji: "放送する", kana: "ほうそうする", meaning: "Phát sóng" },
        { kanji: "番組", kana: "ばんぐみ", meaning: "Chương trình (TV, Radio)" },
        { kanji: "天気予報", kana: "てんきよほう", meaning: "Dự báo thời tiết" },
        { kanji: "地震", kana: "じしん", meaning: "Động đất" },
        { kanji: "津波", kana: "つなみ", meaning: "Sóng thần" },
        { kanji: "台風", kana: "たいふう", meaning: "Bão" },
        { kanji: "火事", kana: "かじ", meaning: "Hỏa hoạn" },
        { kanji: "原因", kana: "げんいん", meaning: "Nguyên nhân" },
        { kanji: "結果", kana: "けっか", meaning: "Kết quả" }
      ]
    },
    2: {
      title: "Viết thư, Email",
      japanese: "手紙・メールを書きましょう",
      words: [
        { kanji: "手紙", kana: "てがみ", meaning: "Bức thư" },
        { kanji: "封筒", kana: "ふうとう", meaning: "Phong bì" },
        { kanji: "便箋", kana: "びんせん", meaning: "Giấy viết thư" },
        { kanji: "切手", kana: "きって", meaning: "Tem thư" },
        { kanji: "貼る", kana: "はる", meaning: "Dán" },
        { kanji: "宛名", kana: "あてな", meaning: "Tên và địa chỉ người nhận" },
        { kanji: "差出人", kana: "さしだしにん", meaning: "Người gửi" },
        { kanji: "返事", kana: "へんじ", meaning: "Hồi âm, trả lời" },
        { kanji: "件名", kana: "けんめい", meaning: "Tiêu đề (email)" },
        { kanji: "送信する", kana: "そうしんする", meaning: "Gửi đi" },
        { kanji: "受信する", kana: "じゅしんする", meaning: "Nhận" },
        { kanji: "返信する", kana: "へんしんする", meaning: "Phản hồi" },
        { kanji: "転送する", kana: "てんそうする", meaning: "Chuyển tiếp (forward)" },
        { kanji: "添付する", kana: "てんぷする", meaning: "Đính kèm" },
        { kanji: "入力する", kana: "にゅうりょくする", meaning: "Nhập vào" },
        { kanji: "削除する", kana: "さくじょする", meaning: "Xóa bỏ" },
        { kanji: "保存する", kana: "ほぞんする", meaning: "Lưu lại" },
        { kanji: "宛先", kana: "あてさき", meaning: "Nơi đến, người nhận" },
        { kanji: "お辞儀する", kana: "おじぎする", meaning: "Cúi chào" },
        { kanji: "挨拶する", kana: "あいさつする", meaning: "Chào hỏi" }
      ]
    },
    3: {
      title: "Điện thoại",
      japanese: "電話をかけましょう",
      words: [
        { kanji: "携帯電話", kana: "けいたいでんわ", meaning: "Điện thoại di động" },
        { kanji: "スマホ", kana: "スマホ", meaning: "Điện thoại thông minh" },
        { kanji: "着信", kana: "ちゃくしん", meaning: "Cuộc gọi đến" },
        { kanji: "発信", kana: "はっしん", meaning: "Cuộc gọi đi" },
        { kanji: "留守番電話", kana: "るすばんでんわ", meaning: "Máy trả lời tự động" },
        { kanji: "伝言", kana: "でんごん", meaning: "Lời nhắn" },
        { kanji: "メッセージ", kana: "メッセージ", meaning: "Tin nhắn" },
        { kanji: "通話", kana: "つうわ", meaning: "Cuộc gọi, đàm thoại" },
        { kanji: "切る", kana: "きる", meaning: "Cúp máy, tắt" },
        { kanji: "繋がる", kana: "つながる", meaning: "Được kết nối, gọi được" },
        { kanji: "繋ぐ", kana: "つなぐ", meaning: "Kết nối" },
        { kanji: "充電する", kana: "じゅうでんする", meaning: "Sạc pin" },
        { kanji: "電池", kana: "でんち", meaning: "Pin" },
        { kanji: "バッテリー", kana: "バッテリー", meaning: "Pin, bình ắc quy" },
        { kanji: "マナーモード", kana: "マナーモード", meaning: "Chế độ im lặng" },
        { kanji: "電源", kana: "でんげん", meaning: "Nguồn điện" },
        { kanji: "切れる", kana: "きれる", meaning: "Bị đứt, hết (pin)" },
        { kanji: "鳴る", kana: "なる", meaning: "Reo, kêu" },
        { kanji: "呼び出す", kana: "よびだす", meaning: "Gọi ra, gọi đến" },
        { kanji: "話し中", kana: "はなしちゅう", meaning: "Đang bận máy" },
        { kanji: "かけ直す", kana: "かけなおす", meaning: "Gọi lại" }
      ]
    },
    4: {
      title: "Sở thích",
      japanese: "趣味について話しましょう",
      words: [
        { kanji: "趣味", kana: "しゅみ", meaning: "Sở thích" },
        { kanji: "興味", kana: "きょうみ", meaning: "Hứng thú" },
        { kanji: "関心", kana: "かんしん", meaning: "Quan tâm" },
        { kanji: "読書", kana: "どくしょ", meaning: "Đọc sách" },
        { kanji: "音楽鑑賞", kana: "おんがくかんしょう", meaning: "Thưởng thức âm nhạc" },
        { kanji: "芸術", kana: "げいじゅつ", meaning: "Nghệ thuật" },
        { kanji: "絵画", kana: "かいが", meaning: "Hội họa, bức tranh" },
        { kanji: "楽器", kana: "がっき", meaning: "Nhạc cụ" },
        { kanji: "ピアノ", kana: "ピアノ", meaning: "Đàn piano" },
        { kanji: "ギター", kana: "ギター", meaning: "Đàn guitar" },
        { kanji: "弾く", kana: "ひく", meaning: "Đánh (đàn)" },
        { kanji: "写真", kana: "しゃしん", meaning: "Bức ảnh" },
        { kanji: "撮影する", kana: "さつえいする", meaning: "Chụp ảnh, quay phim" },
        { kanji: "登山", kana: "とざん", meaning: "Leo núi" },
        { kanji: "ハイキング", kana: "ハイキング", meaning: "Đi bộ đường dài" },
        { kanji: "釣り", kana: "つり", meaning: "Câu cá" },
        { kanji: "キャンプ", kana: "キャンプ", meaning: "Cắm trại" },
        { kanji: "ドライブ", kana: "ドライブ", meaning: "Lái xe dạo mát" },
        { kanji: "集める", kana: "あつめる", meaning: "Sưu tầm, thu thập" },
        { kanji: "切手収集", kana: "きってしゅうしゅう", meaning: "Sưu tầm tem" },
        { kanji: "楽しむ", kana: "たのしむ", meaning: "Thưởng thức, tận hưởng" }
      ]
    },
    5: {
      title: "Sự kiện, lễ hội",
      japanese: "イベント・お祭り",
      words: [
        { kanji: "行事", kana: "ぎょうじ", meaning: "Sự kiện, hội hè" },
        { kanji: "祭り", kana: "まつり", meaning: "Lễ hội" },
        { kanji: "イベント", kana: "イベント", meaning: "Sự kiện" },
        { kanji: "祝日", kana: "しゅくじつ", meaning: "Ngày lễ" },
        { kanji: "休日", kana: "きゅうじつ", meaning: "Ngày nghỉ" },
        { kanji: "年末年始", kana: "ねんまつねんし", meaning: "Cuối năm và đầu năm mới" },
        { kanji: "元日", kana: "がんじつ", meaning: "Ngày đầu năm mới (1/1)" },
        { kanji: "お正月", kana: "おしょうがつ", meaning: "Tết" },
        { kanji: "成人式", kana: "せいじんしき", meaning: "Lễ trưởng thành" },
        { kanji: "卒業式", kana: "そつぎょうしき", meaning: "Lễ tốt nghiệp" },
        { kanji: "入学式", kana: "にゅうがくしき", meaning: "Lễ nhập học" },
        { kanji: "花見", kana: "はなみ", meaning: "Ngắm hoa anh đào" },
        { kanji: "花火大会", kana: "はなびたいかい", meaning: "Lễ hội pháo hoa" },
        { kanji: "クリスマス", kana: "クリスマス", meaning: "Giáng sinh" },
        { kanji: "大晦日", kana: "おおみそか", meaning: "Đêm giao thừa" },
        { kanji: "お盆", kana: "おぼん", meaning: "Lễ Obon" },
        { kanji: "祝う", kana: "いわう", meaning: "Ăn mừng, chúc mừng" },
        { kanji: "お祝い", kana: "おいわい", meaning: "Quà mừng, lời chúc" },
        { kanji: "プレゼント", kana: "プレゼント", meaning: "Quà tặng" },
        { kanji: "贈る", kana: "おくる", meaning: "Tặng, gửi" },
        { kanji: "お土産", kana: "おみやげ", meaning: "Quà lưu niệm, đặc sản" }
      ]
    },
    6: {
      title: "Thể thao",
      japanese: "スポーツ",
      words: [
        { kanji: "スポーツ", kana: "スポーツ", meaning: "Thể thao" },
        { kanji: "運動する", kana: "うんどうする", meaning: "Vận động, tập thể dục" },
        { kanji: "試合", kana: "しあい", meaning: "Trận đấu" },
        { kanji: "大会", kana: "たいかい", meaning: "Đại hội, giải đấu" },
        { kanji: "オリンピック", kana: "オリンピック", meaning: "Thế vận hội" },
        { kanji: "優勝する", kana: "ゆうしょうする", meaning: "Vô địch" },
        { kanji: "勝つ", kana: "かつ", meaning: "Thắng" },
        { kanji: "負ける", kana: "まける", meaning: "Thua" },
        { kanji: "引き分け", kana: "ひきわけ", meaning: "Hòa" },
        { kanji: "応援する", kana: "おうえんする", meaning: "Cổ vũ" },
        { kanji: "選手", kana: "せんしゅ", meaning: "Tuyển thủ, cầu thủ" },
        { kanji: "チーム", kana: "チーム", meaning: "Đội" },
        { kanji: "水泳", kana: "すいえい", meaning: "Bơi lội" },
        { kanji: "野球", kana: "やきゅう", meaning: "Bóng chày" },
        { kanji: "サッカー", kana: "サッカー", meaning: "Bóng đá" },
        { kanji: "テニス", kana: "テニス", meaning: "Tennis" },
        { kanji: "卓球", kana: "たっきゅう", meaning: "Bóng bàn" },
        { kanji: "柔道", kana: "じゅうどう", meaning: "Judo" },
        { kanji: "剣道", kana: "けんどう", meaning: "Kendo" },
        { kanji: "マラソン", kana: "マラソン", meaning: "Marathon" },
        { kanji: "ジョギング", kana: "ジョギング", meaning: "Chạy bộ" },
        { kanji: "記録", kana: "きろく", meaning: "Kỷ lục" }
      ]
    }
  }
};
