export const week1Data = {
  1: { // Tuần 1
    1: { // Ngày 1
      title: "Nhà bếp – phòng khách",
      japanese: "キッチンで / リビングで",
      words: [
        { kanji: "台所", kana: "だいどころ", meaning: "nhà bếp" },
        { kanji: "電子レンジ", kana: "でんしれんじ", meaning: "lò vi sóng" },
        { kanji: "お茶わん", kana: "おちゃわん", meaning: "chén" },
        { kanji: "ワイングラス", kana: "ワイングラス", meaning: "ly uống rượu" },
        { kanji: "コーヒーカップ", kana: "コーヒーカップ", meaning: "tách cà phê" },
        { kanji: "茶わん", kana: "ちゃわん", meaning: "ly, cốc uống trà" },
        { kanji: "湯飲み", kana: "ゆのみ", meaning: "tách trà" },
        { kanji: "ガスレンジ", kana: "ガスレンジ", meaning: "bếp ga" },
        { kanji: "ガスコンロ", kana: "ガスコンロ", meaning: "bếp ga di động, bếp gas" },
        { kanji: "ガラスのコップ", kana: "ガラスのコップ", meaning: "ly thủy tinh" },
        { kanji: "レバー", kana: "レバー", meaning: "cần gạt số, cần điều khiển" },
        { kanji: "流し", kana: "ながし", meaning: "bồn, chậu rửa" },
        { kanji: "居間", kana: "いま", meaning: "phòng khách" },
        { kanji: "リビング", kana: "リビング", meaning: "phòng khách" },
        { kanji: "窓ガラス", kana: "まどガラス", meaning: "cửa kính; kính cửa sổ" },
        { kanji: "雨戸", kana: "あまど", meaning: "cửa sập, cửa che mưa, cửa chớp" },
        { kanji: "網戸", kana: "あみど", meaning: "cửa lưới" },
        { kanji: "天井", kana: "てんじょう", meaning: "trần nhà" },
        { kanji: "床", kana: "ゆか", meaning: "sàn nhà" },
        { kanji: "コンセント", kana: "コンセント", meaning: "ổ cắm điện" },
        { kanji: "コード", kana: "コード", meaning: "dây dẫn" },
        { kanji: "エアコン", kana: "エアコン", meaning: "máy điều hòa" },
        { kanji: "ヒーター", kana: "ヒーター", meaning: "máy sưởi, lò sưởi" },
        { kanji: "カーペット", kana: "カーペット", meaning: "tấm thảm" },
        { kanji: "蛇口", kana: "じゃぐち", meaning: "vòi nước" },
        { kanji: "水道の蛇口をひねる", kana: "すいどうのじゃぐちをひねる", meaning: "mở vòi nước" },
        { kanji: "水が凍る", kana: "みずがこおる", meaning: "nước đông lạnh" },
        { kanji: "氷になる", kana: "こおりになる", meaning: "nước đá, thành nước đá" },
        { kanji: "冷凍して保存する", kana: "れいとうしてほぞんする", meaning: "làm lạnh, làm đông sau đó đem bảo quản" },
        { kanji: "残り物を温める", kana: "のこりものをあたためる", meaning: "làm nóng đồ ăn thừa" },
        { kanji: "ビールを冷やす", kana: "ビールをひやす", meaning: "làm lạnh bia" },
        { kanji: "ビールが冷えている", kana: "ビールがひえている", meaning: "bia được làm lạnh" },
        { kanji: "エアコンのリモコン", kana: "エアコンのリモコン", meaning: "điều khiển điều hòa" },
        { kanji: "スイッチ", kana: "スイッチ", meaning: "công tắc" },
        { kanji: "電源を入れる", kana: "てんげんをいれる", meaning: "mở điện, bật nguồn điện" },
        { kanji: "電源を切る", kana: "てんげんをきる", meaning: "tắt điện, cắt nguồn điện" },
        { kanji: "じゅうたんを敷く", kana: "じゅうたんをしく", meaning: "trải thảm" },
        { kanji: "暖房をつける", kana: "だんぼうをつける", meaning: "bật lò sưởi" },
        { kanji: "冷房が効いている", kana: "れいぼうがきいている", meaning: "máy lạnh đang hoạt động" },
        { kanji: "日当たりがいい", kana: "ひあたりがいい", meaning: "có ánh nắng chiều vào" },
        { kanji: "日当たりが悪い", kana: "ひあたりがわるい", meaning: "không có ánh nắng chiều vào" },
      ]
    },
    2: { // Ngày 2
      title: "Chuẩn bị nấu ăn",
      japanese: "料理の準備をしましょう",
      words: [
        { kanji: "牛肉", kana: "ぎゅうにく", meaning: "thịt bò" },
        { kanji: "ジャガイモ", kana: "ジャガイモ", meaning: "khoai tây" },
        { kanji: "玉ねぎ", kana: "たまねぎ", meaning: "hành tây" },
        { kanji: "水", kana: "みず", meaning: "nước" },
        { kanji: "酒", kana: "さけ", meaning: "rượu, rượu sake Nhật Bản" },
        { kanji: "醤油", kana: "しょうゆ", meaning: "xì dầu, nước tương Nhật Bản" },
        { kanji: "砂糖", kana: "さとう", meaning: "đường" },
        { kanji: "少々", kana: "しょうしょう", meaning: "một chút, một ít" },
        { kanji: "大さじ", kana: "おおさじ", meaning: "thìa múc canh, muỗng canh" },
        { kanji: "小さじ", kana: "こさじ", meaning: "thìa cà phê, muỗng cafe" },
        { kanji: "カップ", kana: "カップ", meaning: "cốc, chén, bát" },
        { kanji: "リットル", kana: "リットル", meaning: "lít" },
        { kanji: "包丁", kana: "ほうちょう", meaning: "con dao; dao làm bếp" },
        { kanji: "まな板", kana: "まないた", meaning: "cái thớt" },
        { kanji: "グラム", kana: "グラム", meaning: "gram" },
        { kanji: "秤", kana: "はかり", meaning: "cái cân" },
        { kanji: "夕食のおかず", kana: "ゆうしょくのおかず", meaning: "đồ ăn tối" },
        { kanji: "栄養のバランスを考える", kana: "えいようのバランスを考える", meaning: "nghĩ đến sự cân bằng dinh dưỡng" },
        { kanji: "栄養", kana: "えいよう", meaning: "dinh dưỡng" },
        { kanji: "バランス", kana: "バランス", meaning: "cân bằng, sự cân bằng" },
        { kanji: "カロリーが高い食品", kana: "カロリーがたかいしょくひん", meaning: "thực phẩm có calo cao" },
        { kanji: "カロリー", kana: "カロリー", meaning: "lượng calo" },
        { kanji: "はかりで量る", kana: "はかりではかる", meaning: "cân, đo bằng cân" },
        { kanji: "調味料", kana: "ちょうみりょう", meaning: "gia vị" },
        { kanji: "酢", kana: "す", meaning: "dấm" },
        { kanji: "塩", kana: "しお", meaning: "muối" },
        { kanji: "皮をむく", kana: "かわをむく", meaning: "bóc vỏ, gọt vỏ, lột vỏ" },
        { kanji: "材料を刻む", kana: "ざいりょうをきざむ", meaning: "thái nguyên liệu" },
        { kanji: "ラップをかける", kana: "ラップをかける", meaning: "bao gói; bọc bằng màng bọc thực phẩm" },
        { kanji: "ラップでくるむ", kana: "ラップでくるむ", meaning: "gói, bọc" },
        { kanji: "ホイル", kana: "ホイル", meaning: "giấy bạc" },
        { kanji: "アルミホイル", kana: "アルミホイル", meaning: "giấy nhôm" }
      ]
    },
    3: { // Ngày 3
      title: "Cách nấu ăn cơ bản",
      japanese: "基本的な料理のやり方",
      words: [
        { kanji: "ふた", kana: "ふた", meaning: "nắp, vung" },
        { kanji: "おたま", kana: "おたま", meaning: "muỗng canh" },
        { kanji: "鍋", kana: "なべ", meaning: "xoong, nồi" },
        { kanji: "フライパン", kana: "フライパン", meaning: "cái chảo rán" },
        { kanji: "炊飯器", kana: "すいはんき", meaning: "nồi cơm điện" },
        { kanji: "しゃもじ", kana: "しゃもじ", meaning: "muỗng múc cơm; muỗng xới cơm" },
        { kanji: "湯を沸かす", kana: "ゆをわかす", meaning: "đun nước cho sôi lên" },
        { kanji: "湯が沸く", kana: "ゆがわく", meaning: "nước sôi" },
        { kanji: "湯が冷める", kana: "ゆがさめる", meaning: "nước để nguội" },
        { kanji: "ご飯を炊く", kana: "ごはんをたく", meaning: "nấu cơm" },
        { kanji: "油を熱する", kana: "あぶらをねっする", meaning: "làm nóng dầu" },
        { kanji: "油で揚げる", kana: "あぶらであげる", meaning: "chiên bằng dầu" },
        { kanji: "煮る", kana: "にる", meaning: "hầm, kho" },
        { kanji: "ゆでる", kana: "ゆでる", meaning: "luộc" },
        { kanji: "いためる", kana: "いためる", meaning: "sào (xào)" },
        { kanji: "蒸す", kana: "むす", meaning: "hấp" },
        { kanji: "混ぜる", kana: "まぜる", meaning: "trộn; để trộn" },
        { kanji: "こげる", kana: "こげる", meaning: "cơm khê, khét, bị cháy" },
        { kanji: "味をつける", kana: "あじをつける", meaning: "cho gia vị; nêm gia vị" },
        { kanji: "塩を加える", kana: "しおをくわえる", meaning: "thêm muối" },
        { kanji: "こしょうを振る", kana: "こしょうをふる", meaning: "rắc tiêu" },
        { kanji: "味見をする", kana: "あじみをする", meaning: "nêm (gia vị)" },
        { kanji: "味を見る", kana: "あじをみる", meaning: "nêm (gia vị)" },
        { kanji: "味が濃い", kana: "あじがこい", meaning: "vị đậm, nồng" },
        { kanji: "味が薄い", kana: "あじがうすい", meaning: "vị nhạt, mỏng (ít gia vị)" },
        { kanji: "辛い", kana: "からい", meaning: "cay; vị cay" },
        { kanji: "塩辛い", kana: "しおからい", meaning: "muối mặn; vị mặn" },
        { kanji: "酸っぱい", kana: "すっぱい", meaning: "chua; vị chua" },
        { kanji: "できあがる", kana: "できあがる", meaning: "hoàn tất" },
        { kanji: "できあがり", kana: "できあがり", meaning: "hoàn tất, làm xong xuôi" }
      ]
    },
    4: { // Ngày 4
      title: "Dọn dẹp nhà cửa",
      japanese: "家をきれいにしましょう",
      words: [
        { kanji: "エプロン", kana: "エプロン", meaning: "tạp dề" },
        { kanji: "ほうき", kana: "ほうき", meaning: "chổi" },
        { kanji: "ちりとり", kana: "ちりとり", meaning: "cái hót rác" },
        { kanji: "ぞうきん", kana: "ぞうきん", meaning: "miếng giẻ (giẻ lau)" },
        { kanji: "バケツ", kana: "バケツ", meaning: "cái xô" },
        { kanji: "エプロンをかける", kana: "エプロンをかける", meaning: "mang tạp dề" },
        { kanji: "エプロンをつける", kana: "エプロンをつける", meaning: "mang tạp dề" },
        { kanji: "ソファーをどける", kana: "ソファーをどける", meaning: "đẩy ghế sang một bên" },
        { kanji: "ソファーがどく", kana: "ソファーがどく", meaning: "ghế được đẩy sang một bên" },
        { kanji: "部屋を散らかす", kana: "へやをちらかす", meaning: "vứt đồ bừa bãi trong phòng" },
        { kanji: "部屋が散らかる", kana: "へやがちらかる", meaning: "đồ đạc bừa bộn trong phòng" },
        { kanji: "部屋を片付ける", kana: "へやをかたづける", meaning: "dọn dẹp phòng" },
        { kanji: "部屋が片づく", kana: "へやがかたづく", meaning: "phòng được dọn dẹp" },
        { kanji: "ジュースをこぼす", kana: "ジュースをこぼす", meaning: "đổ nước trái cây" },
        { kanji: "ジュースがこぼれる", kana: "ジュースがこぼれる", meaning: "ly nước bị đổ" },
        { kanji: "ほこりがたまる", kana: "ほこりがたまる", meaning: "phủ đầy bụi" },
        { kanji: "ほこりがつもる", kana: "ほこりがつもる", meaning: "bụi phủ, bụi bám lại" },
        { kanji: "雪がつもる", kana: "ゆきがつもる", meaning: "tuyết phủ, tuyết đọng lại" },
        { kanji: "掃除機をかける", kana: "そうじきをかける", meaning: "bật máy hút bụi" },
        { kanji: "ほうきで掃く", kana: "ほうきではく", meaning: "quét bằng chổi" },
        { kanji: "水を汲む", kana: "みずをくむ", meaning: "múc nước" },
        { kanji: "ぞうきんをしぼる", kana: "ぞうきんをしぼる", meaning: "vắt giẻ lau" },
        { kanji: "床をふく", kana: "ゆかをふく", meaning: "lau sàn nhà" },
        { kanji: "ふきんで食器をふく", kana: "ふきんでしょっきをふく", meaning: "lau dụng cụ ăn bằng khăn lau" },
        { kanji: "家具をみがく", kana: "かぐをみがく", meaning: "đánh bóng đồ đạc" },
        { kanji: "ブラシでこする", kana: "ブラシでこする", meaning: "đánh, cọ bằng bàn chải" },
        { kanji: "生ゴミ", kana: "なまゴミ", meaning: "rác nhà bếp, rác hữu cơ" },
        { kanji: "燃えるゴミ", kana: "もえるゴミ", meaning: "rác cháy được" },
        { kanji: "燃えないゴミ", kana: "もえないゴミ", meaning: "rác không cháy được" },
        { kanji: "ゴミを分けるのは面倒だ", kana: "ゴミをわけるのはめんどうだ", meaning: "việc phân loại rác thì phiền toái" },
        { kanji: "ゴミを分けるのは面倒くさい", kana: "ゴミをわけるのはめんどうくさい", meaning: "việc phân loại rác thì phiền toái" },
        { kanji: "スリッパをそろえる", kana: "スリッパをそろえる", meaning: "sắp xếp dép" },
        { kanji: "物置にしまう", kana: "ものおきにしまう", meaning: "cất đồ (vào kho chứa đồ)" }
      ]
    },
    5: { // Ngày 5
      title: "Giặt giũ quần áo",
      japanese: "洗濯しましょう",
      words: [
        { kanji: "洗濯物がたまる", kana: "せんたくものがたまる", meaning: "đầy đồ cần giặt" },
        { kanji: "洗濯物をためる", kana: "せんたくものをためる", meaning: "chất đống đồ cần giặt" },
        { kanji: "洗濯物がぬれている", kana: "せんたくものがぬれている", meaning: "đồ giặt còn ướt" },
        { kanji: "洗濯物をぬらす", kana: "せんたくものをぬらす", meaning: "làm ướt đồ giặt" },
        { kanji: "洗濯物が湿っている", kana: "せんたくものがしめっている", meaning: "đồ vẫn ẩm ướt (mới phơi)" },
        { kanji: "洗濯物を干す", kana: "せんたくものをほす", meaning: "phơi đồ giặt" },
        { kanji: "洗濯物が乾く", kana: "せんたくものがかわく", meaning: "đồ giặt đã khô" },
        { kanji: "乾燥機で乾かす", kana: "かんそうきでかわかす", meaning: "làm khô bằng máy sấy" },
        { kanji: "洗濯物を乾燥機で乾かす", kana: "せんたくものをかんそうきでかわかす", meaning: "làm khô quần áo bằng máy sấy" },
        { kanji: "洗濯物が真っ白に仕上がる", kana: "せんたくものがまっしろにしあがる", meaning: "trở nên trắng tinh (sau khi giặt)" },
        { kanji: "洗濯物をたたむ", kana: "せんたくものをたたむ", meaning: "gấp đồ đã giặt" },
        { kanji: "服を汚す", kana: "ふくをよごす", meaning: "làm dơ áo" },
        { kanji: "洗剤を入れる", kana: "せんざいをいれる", meaning: "cho bột giặt vào" },
        { kanji: "洗剤", kana: "せんざい", meaning: "bột giặt, chất tẩy rửa" },
        { kanji: "スーツをクリーニングに出す", kana: "スーツをクリーニングにだす", meaning: "gửi áo vét đến tiệm giặt ủi" },
        { kanji: "コインランドリーで洗濯をする", kana: "コインランドリーでせんたくをする", meaning: "giặt đồ ở tiệm tự động" },
        { kanji: "タオルを干す", kana: "タオルをほす", meaning: "phơi khăn" },
        { kanji: "服をつるす", kana: "ふくをつるす", meaning: "treo quần áo" },
        { kanji: "ワイシャツにアイロンをかける", kana: "ワイシャツにアイロンをかける", meaning: "ủi áo sơ mi" },
        { kanji: "しわを伸ばす", kana: "しわをのばす", meaning: "duỗi thẳng nếp nhăn" },
        { kanji: "しわが伸びる", kana: "しわがのびる", meaning: "nếp nhăn được kéo căng (phẳng ra)" },
        { kanji: "ウールのセーターが縮む", kana: "ウールのセーターがちぢむ", meaning: "áo len bị co rút" },
        { kanji: "ジーンズの色が落ちる", kana: "ジーンズのいろがおちる", meaning: "quần bò bạc màu, phai màu" }
      ]
    },
    6: { // Ngày 6
      title: "Chăm sóc trẻ em & vật nuôi",
      japanese: "育児のやり方・犬を飼う",
      words: [
        { kanji: "犬", kana: "いぬ", meaning: "cún, chó" },
        { kanji: "可愛らしい子供", kana: "かわいらしいこども", meaning: "đứa trẻ đáng yêu" },
        { kanji: "かわいそうな子ども", kana: "かわいそうなこども", meaning: "đứa trẻ tội nghiệp" },
        { kanji: "行儀がいい", kana: "ぎょうぎがいい", meaning: "lễ phép" },
        { kanji: "かしこい", kana: "かしこい", meaning: "thông minh" },
        { kanji: "かしこい子ども", kana: "かしこいこども", meaning: "đứa trẻ khôn ngoan" },
        { kanji: "人なつ（っ）こい", kana: "ひとなつ（っ）こい", meaning: "thân thiện, dễ gần" },
        { kanji: "わがままな子ども", kana: "わがままなこども", meaning: "đứa trẻ ích kỷ" },
        { kanji: "生意気な子ども", kana: "なまいきなこども", meaning: "đứa trẻ xấc xược" },
        { kanji: "生意気な態度", kana: "なまいきなたいど", meaning: "thái độ hỗn láo" },
        { kanji: "子どもを甘やかす", kana: "こどもをあまやかす", meaning: "nuông chiều con" },
        { kanji: "子どもをかわいがる", kana: "こどもをかわいがる", meaning: "yêu thương con" },
        { kanji: "子どもをおんぶする", kana: "こどもをおんぶする", meaning: "cõng con" },
        { kanji: "子どもを抱っこする", kana: "こどもをだっこする", meaning: "bế con" },
        { kanji: "犬がほえる", kana: "いぬがほえる", meaning: "chó sủa" },
        { kanji: "犬が人になれる", kana: "いぬがひとになれる", meaning: "chó quen với người" },
        { kanji: "犬がしっぽを振る", kana: "いぬがしっぽをふる", meaning: "chó vẫy đuôi" },
        { kanji: "犬がうなる", kana: "いぬがうなる", meaning: "chó gầm gừ" },
        { kanji: "犬が穴をほる", kana: "いぬがあなをほる", meaning: "chó đào hố" },
        { kanji: "子育て", kana: "こそだて", meaning: "việc chăm sóc trẻ" },
        { kanji: "育児", kana: "いくじ", meaning: "việc chăm sóc trẻ" },
        { kanji: "幼児", kana: "ようじ", meaning: "trẻ con; đứa trẻ" },
        { kanji: "子どもが成長する", kana: "こどもがせいちょうする", meaning: "đứa trẻ lớn dần" },
        { kanji: "わがままに育つ", kana: "わがままにそだつ", meaning: "(đứa trẻ) lớn lên một cách ích kỷ" },
        { kanji: "えらい", kana: "えらい", meaning: "tài giỏi, ngoan ngoãn" },
        { kanji: "頭をなでる", kana: "あたまをなでる", meaning: "xoa đầu" },
        { kanji: "尻をぶつ", kana: "しりをぶつ", meaning: "đánh vào mông" },
        { kanji: "いたずらをする", kana: "いたずらをする", meaning: "nghịch ngợm" },
        { kanji: "いたずらな", kana: "いたずらな", meaning: "nghịch ngợm, đùa nghịch" },
        { kanji: "手をつなぐ", kana: "てをつなぐ", meaning: "nắm tay" },
        { kanji: "手をはなす", kana: "てをはなす", meaning: "buông tay, rời tay ra" },
        { kanji: "子どもが迷子になる", kana: "こどもがまいごになる", meaning: "đứa trẻ đi lạc" },
        { kanji: "子どもが母親の後をついていく", kana: "こどもがははおやのあとをついていく", meaning: "đứa trẻ đi theo sau mẹ" },
        { kanji: "犬を飼う", kana: "いぬをかう", meaning: "nuôi chó" },
        { kanji: "散歩に連れていく", kana: "さんぽにつれていく", meaning: "dẫn đi dạo" },
        { kanji: "犬にえさをやる", kana: "いぬにえさをやる", meaning: "cho chó ăn" },
        { kanji: "犬にえさを与える", kana: "いぬにえさをあたえる", meaning: "cho chó ăn" }
      ]
    }
  }
};
