export const week3Data = {
  3: {
    1: {
      title: "Cửa hàng, bảng hiệu",
      japanese: "お店に行きましょう",
      words: [
        { kanji: "営業", kana: "えいぎょう", meaning: "Kinh doanh, doanh nghiệp" },
        { kanji: "休業", kana: "きゅうぎょう", meaning: "Đóng cửa, nghỉ bán" },
        { kanji: "定休日", kana: "ていきゅうび", meaning: "Ngày nghỉ định kỳ" },
        { kanji: "準備中", kana: "じゅんびちゅう", meaning: "Đang chuẩn bị" },
        { kanji: "営業中", kana: "えいぎょうちゅう", meaning: "Đang mở cửa" },
        { kanji: "広告", kana: "こうこく", meaning: "Quảng cáo" },
        { kanji: "看板", kana: "かんばん", meaning: "Bảng hiệu" },
        { kanji: "割引", kana: "わりびき", meaning: "Giảm giá" },
        { kanji: "半額", kana: "はんがく", meaning: "Nửa giá" },
        { kanji: "特売", kana: "とくばい", meaning: "Bán hạ giá đặc biệt" },
        { kanji: "特売品", kana: "とくばいひん", meaning: "Hàng giảm giá đặc biệt" },
        { kanji: "閉店", kana: "へいてん", meaning: "Đóng cửa tiệm" },
        { kanji: "開店", kana: "かいてん", meaning: "Mở cửa tiệm" },
        { kanji: "無料", kana: "むりょう", meaning: "Miễn phí" },
        { kanji: "タダ", kana: "タダ", meaning: "Miễn phí (văn nói)" },
        { kanji: "有料", kana: "ゆうりょう", meaning: "Có phí" },
        { kanji: "レジ", kana: "レジ", meaning: "Quầy thu ngân" },
        { kanji: "お釣り", kana: "おつり", meaning: "Tiền thối lại" },
        { kanji: "レシート", kana: "レシート", meaning: "Hóa đơn, biên lai" },
        { kanji: "領収書", kana: "りょうしゅうしょ", meaning: "Biên lai, hóa đơn đỏ" },
        { kanji: "袋", kana: "ふくろ", meaning: "Túi, bao" },
        { kanji: "紙袋", kana: "かみぶくろ", meaning: "Túi giấy" },
        { kanji: "ビニール袋", kana: "ビニールぶくろ", meaning: "Túi ni lông" }
      ]
    },
    2: {
      title: "Đi mua sắm (1)",
      japanese: "買い物をしましょう①",
      words: [
        { kanji: "値段", kana: "ねだん", meaning: "Giá cả" },
        { kanji: "定価", kana: "ていか", meaning: "Giá cố định, giá niêm yết" },
        { kanji: "価格", kana: "かかく", meaning: "Giá cả, mức giá" },
        { kanji: "値引きする", kana: "ねびきする", meaning: "Giảm giá" },
        { kanji: "おまけする", kana: "おまけする", meaning: "Giảm giá thêm, tặng kèm" },
        { kanji: "税金", kana: "ぜいきん", meaning: "Tiền thuế" },
        { kanji: "消費税", kana: "しょうひぜい", meaning: "Thuế tiêu dùng" },
        { kanji: "商品", kana: "しょうひん", meaning: "Hàng hóa, sản phẩm" },
        { kanji: "品物", kana: "しなもの", meaning: "Hàng hóa" },
        { kanji: "サイズ", kana: "サイズ", meaning: "Kích cỡ" },
        { kanji: "デザイン", kana: "デザイン", meaning: "Thiết kế" },
        { kanji: "色", kana: "いろ", meaning: "Màu sắc" },
        { kanji: "柄", kana: "がら", meaning: "Hoa văn, họa tiết" },
        { kanji: "無地", kana: "むじ", meaning: "Trơn (không có hoa văn)" },
        { kanji: "カタログ", kana: "カタログ", meaning: "Cuốn mục lục, catalogue" },
        { kanji: "試着する", kana: "しちゃくする", meaning: "Mặc thử" },
        { kanji: "似合う", kana: "にあう", meaning: "Phù hợp, hợp" },
        { kanji: "ぴったり", kana: "ぴったり", meaning: "Vừa vặn" },
        { kanji: "気に入る", kana: "きにいる", meaning: "Yêu thích, ưng ý" },
        { kanji: "お気に入り", kana: "おきにいり", meaning: "Món đồ yêu thích" },
        { kanji: "現金", kana: "げんきん", meaning: "Tiền mặt" },
        { kanji: "クレジットカード", kana: "クレジットカード", meaning: "Thẻ tín dụng" },
        { kanji: "支払う", kana: "しはらう", meaning: "Chi trả, thanh toán" },
        { kanji: "お勘定", kana: "おかんじょう", meaning: "Thanh toán, tính tiền" }
      ]
    },
    3: {
      title: "Đi mua sắm (2)",
      japanese: "買い物をしましょう②",
      words: [
        { kanji: "注文する", kana: "ちゅうもんする", meaning: "Đặt hàng, gọi món" },
        { kanji: "配達する", kana: "はいたつする", meaning: "Giao hàng" },
        { kanji: "届ける", kana: "とどける", meaning: "Giao đến" },
        { kanji: "送料", kana: "そうりょう", meaning: "Phí gửi hàng" },
        { kanji: "宅配便", kana: "たくはいびん", meaning: "Dịch vụ chuyển phát tận nhà" },
        { kanji: "返品する", kana: "へんぴんする", meaning: "Trả lại hàng" },
        { kanji: "交換する", kana: "こうかんする", meaning: "Đổi hàng" },
        { kanji: "品切れ", kana: "しなぎれ", meaning: "Hết hàng" },
        { kanji: "売り切れ", kana: "うりきれ", meaning: "Bán hết" },
        { kanji: "売り切れる", kana: "うりきれる", meaning: "Bán sạch, cháy hàng" },
        { kanji: "在庫", kana: "ざいこ", meaning: "Hàng tồn kho" },
        { kanji: "本物", kana: "ほんもの", meaning: "Đồ thật" },
        { kanji: "偽物", kana: "にせもの", meaning: "Đồ giả" },
        { kanji: "新品", kana: "しんぴん", meaning: "Đồ mới" },
        { kanji: "中古", kana: "ちゅうこ", meaning: "Đồ cũ, secondhand" },
        { kanji: "量る", kana: "はかる", meaning: "Cân, đo" },
        { kanji: "新鮮な", kana: "しんせんな", meaning: "Tươi mới" },
        { kanji: "腐る", kana: "くさる", meaning: "Thiu, thối, hỏng" },
        { kanji: "包む", kana: "つつむ", meaning: "Bọc, gói" },
        { kanji: "包装する", kana: "ほうそうする", meaning: "Đóng gói" }
      ]
    },
    4: {
      title: "Ăn uống (1)",
      japanese: "食事をしましょう①",
      words: [
        { kanji: "メニュー", kana: "メニュー", meaning: "Thực đơn" },
        { kanji: "バイキング", kana: "バイキング", meaning: "Buffet" },
        { kanji: "食べ放題", kana: "たべほうだい", meaning: "Ăn thỏa thích" },
        { kanji: "飲み放題", kana: "のみほうだい", meaning: "Uống thỏa thích" },
        { kanji: "追加する", kana: "ついかする", meaning: "Gọi thêm, thêm vào" },
        { kanji: "お代わり", kana: "おかわり", meaning: "Thêm bát nữa, thêm cốc nữa" },
        { kanji: "おしぼり", kana: "おしぼり", meaning: "Khăn ướt" },
        { kanji: "乾杯する", kana: "かんぱいする", meaning: "Cạn ly, nâng ly" },
        { kanji: "酔う", kana: "よう", meaning: "Say" },
        { kanji: "酔っ払う", kana: "よっぱらう", meaning: "Say xỉn" },
        { kanji: "おつまみ", kana: "おつまみ", meaning: "Đồ nhắm" },
        { kanji: "おかず", kana: "おかず", meaning: "Thức ăn kèm, món mặn" },
        { kanji: "お弁当", kana: "おべんとう", meaning: "Cơm hộp" },
        { kanji: "外食する", kana: "がいしょくする", meaning: "Ăn ngoài" },
        { kanji: "ごちそうする", kana: "ごちそうする", meaning: "Chiêu đãi" },
        { kanji: "おごる", kana: "おごる", meaning: "Khao, bao" },
        { kanji: "奢る", kana: "おごる", meaning: "Khao (Hán tự)" },
        { kanji: "食欲", kana: "しょくよく", meaning: "Sự thèm ăn" },
        { kanji: "かむ", kana: "かむ", meaning: "Nhai" },
        { kanji: "味わう", kana: "あじわう", meaning: "Thưởng thức" },
        { kanji: "残す", kana: "のこす", meaning: "Để thừa, chừa lại" },
        { kanji: "残る", kana: "のこる", meaning: "Còn thừa" }
      ]
    },
    5: {
      title: "Ăn uống (2)",
      japanese: "食事をしましょう②",
      words: [
        { kanji: "禁煙", kana: "きんえん", meaning: "Cấm hút thuốc" },
        { kanji: "禁煙席", kana: "きんえんせき", meaning: "Ghế cấm hút thuốc" },
        { kanji: "喫煙席", kana: "きつえんせき", meaning: "Ghế được hút thuốc" },
        { kanji: "満席", kana: "まんせき", meaning: "Kín chỗ, hết chỗ" },
        { kanji: "空席", kana: "くうせき", meaning: "Ghế trống" },
        { kanji: "お勘定", kana: "おかんじょう", meaning: "Tính tiền, thanh toán" },
        { kanji: "お会計", kana: "おかいけい", meaning: "Thanh toán, tính tiền" },
        { kanji: "割り勘にする", kana: "わりかんにする", meaning: "Chia đều tiền trả" },
        { kanji: "別々に", kana: "べつべつに", meaning: "Trả riêng" },
        { kanji: "奢る", kana: "おごる", meaning: "Khao" },
        { kanji: "ごちそうになる", kana: "ごちそうになる", meaning: "Được khao, được chiêu đãi" },
        { kanji: "クレジットカード", kana: "クレジットカード", meaning: "Thẻ tín dụng" },
        { kanji: "お札", kana: "おさつ", meaning: "Tiền giấy" },
        { kanji: "硬貨", kana: "こうか", meaning: "Tiền xu" },
        { kanji: "小銭", kana: "こぜに", meaning: "Tiền lẻ" },
        { kanji: "レシート", kana: "レシート", meaning: "Biên lai" },
        { kanji: "領収書", kana: "りょうしゅうしょ", meaning: "Hóa đơn" },
        { kanji: "店員", kana: "てんいん", meaning: "Nhân viên quán" },
        { kanji: "ウェイター", kana: "ウェイター", meaning: "Phục vụ nam" },
        { kanji: "ウェイトレス", kana: "ウェイトレス", meaning: "Phục vụ nữ" }
      ]
    },
    6: {
      title: "Thông báo dự định",
      japanese: "予定を知らせましょう",
      words: [
        { kanji: "予定", kana: "よてい", meaning: "Dự định" },
        { kanji: "変更する", kana: "へんこうする", meaning: "Thay đổi" },
        { kanji: "キャンセルする", kana: "キャンセルする", meaning: "Hủy bỏ" },
        { kanji: "延期する", kana: "えんきする", meaning: "Trì hoãn, hoãn lại" },
        { kanji: "中止する", kana: "ちゅうしする", meaning: "Hủy bỏ, dừng lại" },
        { kanji: "間に合う", kana: "まにあう", meaning: "Kịp giờ" },
        { kanji: "間に合わせる", kana: "まにあわせる", meaning: "Làm cho kịp" },
        { kanji: "遅れる", kana: "おくれる", meaning: "Trễ, muộn" },
        { kanji: "遅刻する", kana: "ちこくする", meaning: "Đến trễ" },
        { kanji: "確認する", kana: "かくにんする", meaning: "Xác nhận" },
        { kanji: "連絡する", kana: "れんらくする", meaning: "Liên lạc" },
        { kanji: "都合がいい", kana: "つごうがいい", meaning: "Thuận tiện (về thời gian)" },
        { kanji: "都合が悪い", kana: "つごうがわるい", meaning: "Không thuận tiện" },
        { kanji: "空く", kana: "あく", meaning: "Trống, rảnh rỗi" },
        { kanji: "予定が空く", kana: "よていがあく", meaning: "Lịch trình trống" },
        { kanji: "待ち合わせる", kana: "まちあわせる", meaning: "Hẹn gặp nhau" },
        { kanji: "約束する", kana: "やくそくする", meaning: "Hẹn, hứa" },
        { kanji: "すっぽかす", kana: "すっぽかす", meaning: "Bỏ bom, cho leo cây" },
        { kanji: "断る", kana: "ことわる", meaning: "Từ chối" },
        { kanji: "知らせる", kana: "しらせる", meaning: "Thông báo" }
      ]
    }
  }
};
