export const week5Data = {
  5: {
    1: {
      title: "Trường học (1)",
      japanese: "学校について①",
      words: [
        { kanji: "入学する", kana: "にゅうがくする", meaning: "Nhập học" },
        { kanji: "卒業する", kana: "そつぎょうする", meaning: "Tốt nghiệp" },
        { kanji: "進学する", kana: "しんがくする", meaning: "Học lên cao" },
        { kanji: "退学する", kana: "たいがくする", meaning: "Thôi học, bị đuổi học" },
        { kanji: "休学する", kana: "きゅうがくする", meaning: "Nghỉ học tạm thời" },
        { kanji: "専攻", kana: "せんこう", meaning: "Chuyên ngành" },
        { kanji: "学部", kana: "がくぶ", meaning: "Khoa (trong trường đại học)" },
        { kanji: "学科", kana: "がっか", meaning: "Môn học, khoa" },
        { kanji: "学費", kana: "がくひ", meaning: "Học phí" },
        { kanji: "奨学金", kana: "しょうがくきん", meaning: "Học bổng" },
        { kanji: "大学院", kana: "だいがくいん", meaning: "Cao học" },
        { kanji: "専門学校", kana: "せんもんがっこう", meaning: "Trường nghề" },
        { kanji: "予備校", kana: "よびこう", meaning: "Trường dự bị, lò luyện thi" },
        { kanji: "塾", kana: "じゅく", meaning: "Lớp học thêm" },
        { kanji: "教授", kana: "きょうじゅ", meaning: "Giáo sư" },
        { kanji: "講師", kana: "こうし", meaning: "Giảng viên" },
        { kanji: "留学生", kana: "りゅうがくせい", meaning: "Du học sinh" },
        { kanji: "受験する", kana: "じゅけんする", meaning: "Dự thi" },
        { kanji: "合格する", kana: "ごうかくする", meaning: "Đậu, đỗ" },
        { kanji: "落ちる", kana: "おちる", meaning: "Rớt, trượt" }
      ]
    },
    2: {
      title: "Trường học (2)",
      japanese: "学校について②",
      words: [
        { kanji: "授業", kana: "じゅぎょう", meaning: "Tiết học" },
        { kanji: "講義", kana: "こうぎ", meaning: "Bài giảng" },
        { kanji: "休講", kana: "きゅうこう", meaning: "Nghỉ dạy" },
        { kanji: "補講", kana: "ほこう", meaning: "Học bù" },
        { kanji: "提出する", kana: "ていしゅつする", meaning: "Nộp (bài)" },
        { kanji: "課題", kana: "かだい", meaning: "Bài tập lớn, chủ đề" },
        { kanji: "宿題", kana: "しゅくだい", meaning: "Bài tập về nhà" },
        { kanji: "レポート", kana: "レポート", meaning: "Báo cáo, tiểu luận" },
        { kanji: "試験", kana: "しけん", meaning: "Kỳ thi" },
        { kanji: "テスト", kana: "テスト", meaning: "Bài kiểm tra" },
        { kanji: "成績", kana: "せいせき", meaning: "Thành tích, điểm số" },
        { kanji: "評価する", kana: "ひょうかする", meaning: "Đánh giá" },
        { kanji: "単位", kana: "たんい", meaning: "Tín chỉ" },
        { kanji: "単位を取る", kana: "たんいをとる", meaning: "Lấy tín chỉ" },
        { kanji: "単位を落とす", kana: "たんいをおとす", meaning: "Rớt tín chỉ" },
        { kanji: "サークル", kana: "サークル", meaning: "Câu lạc bộ" },
        { kanji: "ゼミ", kana: "ゼミ", meaning: "Hội thảo, seminar" },
        { kanji: "研究する", kana: "けんきゅうする", meaning: "Nghiên cứu" },
        { kanji: "論文", kana: "ろんぶん", meaning: "Luận văn" },
        { kanji: "実験する", kana: "じっけんする", meaning: "Thực nghiệm, thí nghiệm" }
      ]
    },
    3: {
      title: "Tìm việc, phỏng vấn",
      japanese: "就職・面接",
      words: [
        { kanji: "就職する", kana: "しゅうしょくする", meaning: "Tìm việc, xin việc" },
        { kanji: "就職活動", kana: "しゅうしょくかつどう", meaning: "Hoạt động tìm việc" },
        { kanji: "求人", kana: "きゅうじん", meaning: "Tuyển dụng" },
        { kanji: "応募する", kana: "おうぼする", meaning: "Ứng tuyển" },
        { kanji: "履歴書", kana: "りれきしょ", meaning: "Sơ yếu lý lịch" },
        { kanji: "面接", kana: "めんせつ", meaning: "Phỏng vấn" },
        { kanji: "採用する", kana: "さいようする", meaning: "Tuyển dụng, nhận vào làm" },
        { kanji: "不採用", kana: "ふさいよう", meaning: "Không được nhận, trượt" },
        { kanji: "雇う", kana: "やとう", meaning: "Thuê, mướn" },
        { kanji: "給料", kana: "きゅうりょう", meaning: "Lương" },
        { kanji: "ボーナス", kana: "ボーナス", meaning: "Tiền thưởng" },
        { kanji: "契約", kana: "けいやく", meaning: "Hợp đồng" },
        { kanji: "正社員", kana: "せいしゃいん", meaning: "Nhân viên chính thức" },
        { kanji: "アルバイト", kana: "アルバイト", meaning: "Việc làm thêm" },
        { kanji: "パート", kana: "パート", meaning: "Việc bán thời gian" },
        { kanji: "派遣", kana: "はけん", meaning: "Phái cử" },
        { kanji: "募集する", kana: "ぼしゅうする", meaning: "Tuyển mộ, chiêu mộ" },
        { kanji: "資格", kana: "しかく", meaning: "Bằng cấp, tư cách" },
        { kanji: "条件", kana: "じょうけん", meaning: "Điều kiện" },
        { kanji: "交通費", kana: "こうつうひ", meaning: "Phí đi lại" }
      ]
    },
    4: {
      title: "Tại công ty (1)",
      japanese: "会社で①",
      words: [
        { kanji: "出勤する", kana: "しゅっきんする", meaning: "Đi làm" },
        { kanji: "退勤する", kana: "たいきんする", meaning: "Tan làm" },
        { kanji: "欠勤する", kana: "けっきんする", meaning: "Nghỉ làm" },
        { kanji: "遅刻する", kana: "ちこくする", meaning: "Đến trễ" },
        { kanji: "早退する", kana: "そうたいする", meaning: "Về sớm" },
        { kanji: "残業する", kana: "ざんぎょうする", meaning: "Làm thêm giờ" },
        { kanji: "休憩する", kana: "きゅうけいする", meaning: "Nghỉ giải lao" },
        { kanji: "有給休暇", kana: "ゆうきゅうきゅうか", meaning: "Nghỉ phép có lương" },
        { kanji: "出張する", kana: "しゅっちょうする", meaning: "Đi công tác" },
        { kanji: "転勤する", kana: "てんきんする", meaning: "Chuyển công tác" },
        { kanji: "異動する", kana: "いどうする", meaning: "Điều chuyển bộ phận" },
        { kanji: "退職する", kana: "たいしょくする", meaning: "Nghỉ việc" },
        { kanji: "辞める", kana: "やめる", meaning: "Từ bỏ, nghỉ" },
        { kanji: "クビになる", kana: "クビになる", meaning: "Bị sa thải" },
        { kanji: "定年", kana: "ていねん", meaning: "Tuổi về hưu" },
        { kanji: "タイムカード", kana: "タイムカード", meaning: "Thẻ chấm công" },
        { kanji: "シフト", kana: "シフト", meaning: "Ca làm việc" },
        { kanji: "担当する", kana: "たんとうする", meaning: "Đảm nhận, phụ trách" },
        { kanji: "責任", kana: "せきにん", meaning: "Trách nhiệm" }
      ]
    },
    5: {
      title: "Tại công ty (2)",
      japanese: "会社で②",
      words: [
        { kanji: "社長", kana: "しゃちょう", meaning: "Giám đốc" },
        { kanji: "部長", kana: "ぶちょう", meaning: "Trưởng phòng" },
        { kanji: "課長", kana: "かちょう", meaning: "Tổ trưởng, trưởng khoa" },
        { kanji: "上司", kana: "じょうし", meaning: "Cấp trên" },
        { kanji: "部下", kana: "ぶか", meaning: "Cấp dưới" },
        { kanji: "先輩", kana: "せんぱい", meaning: "Tiền bối" },
        { kanji: "後輩", kana: "こうはい", meaning: "Hậu bối" },
        { kanji: "同僚", kana: "どうりょう", meaning: "Đồng nghiệp" },
        { kanji: "会議", kana: "かいぎ", meaning: "Cuộc họp" },
        { kanji: "打ち合わせ", kana: "うちあわせ", meaning: "Họp bàn, thảo luận" },
        { kanji: "提案する", kana: "ていあんする", meaning: "Đề xuất" },
        { kanji: "賛成する", kana: "さんせいする", meaning: "Tán thành" },
        { kanji: "反対する", kana: "はんたいする", meaning: "Phản đối" },
        { kanji: "意見", kana: "いけん", meaning: "Ý kiến" },
        { kanji: "決定する", kana: "けっていする", meaning: "Quyết định" },
        { kanji: "スケジュール", kana: "スケジュール", meaning: "Lịch trình" },
        { kanji: "締め切り", kana: "しめきり", meaning: "Hạn chót" },
        { kanji: "企画", kana: "きかく", meaning: "Kế hoạch, dự án" },
        { kanji: "プレゼン", kana: "プレゼン", meaning: "Thuyết trình" },
        { kanji: "名刺", kana: "めいし", meaning: "Danh thiếp" },
        { kanji: "交換する", kana: "こうかんする", meaning: "Trao đổi" }
      ]
    },
    6: {
      title: "Máy tính, PC",
      japanese: "パソコン",
      words: [
        { kanji: "パソコン", kana: "パソコン", meaning: "Máy tính cá nhân" },
        { kanji: "電源", kana: "でんげん", meaning: "Nguồn điện" },
        { kanji: "入力する", kana: "にゅうりょくする", meaning: "Nhập liệu" },
        { kanji: "保存する", kana: "ほぞんする", meaning: "Lưu, bảo quản" },
        { kanji: "削除する", kana: "さくじょする", meaning: "Xóa bỏ" },
        { kanji: "印刷する", kana: "いんさつする", meaning: "In ấn" },
        { kanji: "プリントする", kana: "プリントする", meaning: "In" },
        { kanji: "検索する", kana: "けんさくする", meaning: "Tìm kiếm" },
        { kanji: "画面", kana: "がめん", meaning: "Màn hình" },
        { kanji: "キーボード", kana: "キーボード", meaning: "Bàn phím" },
        { kanji: "マウス", kana: "マウス", meaning: "Chuột máy tính" },
        { kanji: "ファイル", kana: "ファイル", meaning: "Tệp tin, file" },
        { kanji: "フォルダ", kana: "フォルダ", meaning: "Thư mục, folder" },
        { kanji: "コピーする", kana: "コピーする", meaning: "Sao chép" },
        { kanji: "貼り付ける", kana: "はりつける", meaning: "Dán (paste)" },
        { kanji: "クリックする", kana: "クリックする", meaning: "Nhấp chuột" },
        { kanji: "インターネット", kana: "インターネット", meaning: "Mạng internet" },
        { kanji: "ホームページ", kana: "ホームページ", meaning: "Trang chủ" },
        { kanji: "ダウンロードする", kana: "ダウンロードする", meaning: "Tải xuống" },
        { kanji: "インストールする", kana: "インストールする", meaning: "Cài đặt phần mềm" },
        { kanji: "再起動する", kana: "さいきどうする", meaning: "Khởi động lại" },
        { kanji: "フリーズする", kana: "フリーズする", meaning: "Bị treo máy" }
      ]
    }
  }
};
