export const week2Data = {
  2: {
    1: {
      title: "Lập kế hoạch",
      japanese: "計画を立てましょう",
      words: [
        { kanji: "予定", kana: "よてい", meaning: "Dự định, kế hoạch" },
        { kanji: "計画する", kana: "けいかくする", meaning: "Lập kế hoạch" },
        { kanji: "日にち", kana: "ひにち", meaning: "Ngày tháng" },
        { kanji: "日帰り", kana: "ひがえり", meaning: "Đi về trong ngày" },
        { kanji: "一泊二日", kana: "いっぱくふつか", meaning: "2 ngày 1 đêm" },
        { kanji: "二泊三日", kana: "にはくみっか", meaning: "3 ngày 2 đêm" },
        { kanji: "宿泊", kana: "しゅくはく", meaning: "Trọ lại, ngủ lại" },
        { kanji: "滞在", kana: "たいざい", meaning: "Lưu trú, ở lại" },
        { kanji: "団体旅行", kana: "だんたいりょこう", meaning: "Du lịch theo đoàn" },
        { kanji: "個人旅行", kana: "こじんりょこう", meaning: "Du lịch cá nhân" },
        { kanji: "名所", kana: "めいしょ", meaning: "Danh lam thắng cảnh" },
        { kanji: "温泉", kana: "おんせん", meaning: "Suối nước nóng" },
        { kanji: "観光", kana: "かんこう", meaning: "Tham quan, du lịch" },
        { kanji: "見物", kana: "けんぶつ", meaning: "Tham quan, ngắm cảnh" },
        { kanji: "抜け道", kana: "ぬけみち", meaning: "Đường tắt" },
        { kanji: "待ち合わせる", kana: "まちあわせる", meaning: "Hẹn gặp" },
        { kanji: "合わせる", kana: "あわせる", meaning: "Điều chỉnh, làm cho khớp" },
        { kanji: "休む", kana: "やすむ", meaning: "Nghỉ ngơi" },
        { kanji: "休暇", kana: "きゅうか", meaning: "Kỳ nghỉ" },
        { kanji: "調べる", kana: "しらべる", meaning: "Tra cứu, tìm hiểu" },
        { kanji: "準備する", kana: "じゅんびする", meaning: "Chuẩn bị" },
        { kanji: "予約する", kana: "よやくする", meaning: "Đặt trước" },
        { kanji: "キャンセルする", kana: "キャンセルする", meaning: "Hủy bỏ" },
        { kanji: "荷物", kana: "にもつ", meaning: "Hành lý" },
        { kanji: "トランク", kana: "トランク", meaning: "Va li, cốp xe" },
        { kanji: "切符", kana: "きっぷ", meaning: "Vé" }
      ]
    },
    2: {
      title: "Đi tàu (1)",
      japanese: "電車に乗りましょう①",
      words: [
        { kanji: "乗客", kana: "じょうきゃく", meaning: "Hành khách" },
        { kanji: "発車する", kana: "はっしゃする", meaning: "Khởi hành, xuất phát" },
        { kanji: "停車する", kana: "ていしゃする", meaning: "Dừng xe, dừng tàu" },
        { kanji: "乗車する", kana: "じょうしゃする", meaning: "Lên xe, lên tàu" },
        { kanji: "下車する", kana: "げしゃする", meaning: "Xuống xe, xuống tàu" },
        { kanji: "特急", kana: "とっきゅう", meaning: "Tàu tốc hành đặc biệt" },
        { kanji: "急行", kana: "きゅうこう", meaning: "Tàu tốc hành" },
        { kanji: "快速", kana: "かいそく", meaning: "Tàu nhanh" },
        { kanji: "各駅停車", kana: "かくえきていしゃ", meaning: "Tàu đỗ ở mọi ga" },
        { kanji: "時刻表", kana: "じこくひょう", meaning: "Thời gian biểu, lịch trình" },
        { kanji: "ダイヤ", kana: "ダイヤ", meaning: "Lịch trình tàu" },
        { kanji: "終点", kana: "しゅうてん", meaning: "Trạm cuối" },
        { kanji: "上り", kana: "のぼり", meaning: "Lên (tàu đi về Tokyo)" },
        { kanji: "下り", kana: "くだり", meaning: "Xuống (tàu đi ra khỏi Tokyo)" },
        { kanji: "改札口", kana: "かいさつぐち", meaning: "Cổng soát vé" },
        { kanji: "切符売り場", kana: "きっぷうりば", meaning: "Nơi bán vé" },
        { kanji: "券売機", kana: "けんばいき", meaning: "Máy bán vé tự động" },
        { kanji: "精算機", kana: "せいさんき", meaning: "Máy thanh toán bổ sung" },
        { kanji: "ホーム", kana: "ホーム", meaning: "Sân ga" },
        { kanji: "白線", kana: "はくせん", meaning: "Vạch trắng" },
        { kanji: "黄色い線", kana: "きいろいせん", meaning: "Vạch vàng" },
        { kanji: "下がる", kana: "さがる", meaning: "Lùi lại" },
        { kanji: "内側", kana: "うちがわ", meaning: "Bên trong" },
        { kanji: "外側", kana: "そとがわ", meaning: "Bên ngoài" },
        { kanji: "通過する", kana: "つうかする", meaning: "Đi qua, lướt qua" }
      ]
    },
    3: {
      title: "Đi tàu (2)",
      japanese: "電車に乗りましょう②",
      words: [
        { kanji: "座席", kana: "ざせき", meaning: "Chỗ ngồi" },
        { kanji: "指定席", kana: "していせき", meaning: "Ghế chỉ định" },
        { kanji: "自由席", kana: "じゆうせき", meaning: "Ghế tự do" },
        { kanji: "通路側", kana: "つうろがわ", meaning: "Phía lối đi" },
        { kanji: "窓側", kana: "まどがわ", meaning: "Phía cửa sổ" },
        { kanji: "優先席", kana: "ゆうせんせき", meaning: "Ghế ưu tiên" },
        { kanji: "お年寄り", kana: "おとしより", meaning: "Người già" },
        { kanji: "老人", kana: "ろうじん", meaning: "Người già" },
        { kanji: "お年寄りに席を譲る", kana: "おとしよりにせきをゆずる", meaning: "Nhường ghế cho người già" },
        { kanji: "体の不自由な人", kana: "からだのふじゆうなひと", meaning: "Người khuyết tật" },
        { kanji: "ちかん", kana: "ちかん", meaning: "Kẻ sàm sỡ" },
        { kanji: "すり", kana: "すり", meaning: "Kẻ móc túi" },
        { kanji: "満員電車", kana: "まんいんでんしゃ", meaning: "Tàu điện chật kín người" },
        { kanji: "空いている", kana: "あいている", meaning: "Trống, vắng" },
        { kanji: "混む", kana: "こむ", meaning: "Đông đúc" },
        { kanji: "通勤する", kana: "つうきんする", meaning: "Đi làm" },
        { kanji: "通学する", kana: "つうがくする", meaning: "Đi học" },
        { kanji: "乗り換える", kana: "のりかえる", meaning: "Đổi tàu, chuyển tuyến" },
        { kanji: "乗り遅れる", kana: "のりおくれる", meaning: "Lỡ tàu, trễ tàu" },
        { kanji: "乗り越す", kana: "のりこす", meaning: "Đi quá ga" },
        { kanji: "乗り過ごす", kana: "のりすごす", meaning: "Đi lố ga (do ngủ quên)" },
        { kanji: "踏む", kana: "ふむ", meaning: "Dẫm lên" },
        { kanji: "車内", kana: "しゃない", meaning: "Trong xe" },
        { kanji: "携帯電話", kana: "けいたいでんわ", meaning: "Điện thoại di động" },
        { kanji: "マナー", kana: "マナー", meaning: "Phép lịch sự, văn hóa" }
      ]
    },
    4: {
      title: "Lái xe ô tô (1)",
      japanese: "車に乗りましょう①",
      words: [
        { kanji: "運転免許", kana: "うんてんめんきょ", meaning: "Bằng lái xe" },
        { kanji: "レンタカー", kana: "レンタカー", meaning: "Xe thuê" },
        { kanji: "渋滞する", kana: "じゅうたいする", meaning: "Tắc đường" },
        { kanji: "道路", kana: "どうろ", meaning: "Đường bộ" },
        { kanji: "高速道路", kana: "こうそくどうろ", meaning: "Đường cao tốc" },
        { kanji: "安全な", kana: "あんぜんな", meaning: "An toàn" },
        { kanji: "危険な", kana: "きけんな", meaning: "Nguy hiểm" },
        { kanji: "車道", kana: "しゃどう", meaning: "Đường dành cho xe" },
        { kanji: "歩道", kana: "ほどう", meaning: "Đường dành cho người đi bộ" },
        { kanji: "交通規則", kana: "こうつうきそく", meaning: "Luật giao thông" },
        { kanji: "信号", kana: "しんごう", meaning: "Đèn giao thông" },
        { kanji: "交差点", kana: "こうさてん", meaning: "Ngã tư" },
        { kanji: "踏切", kana: "ふみきり", meaning: "Chỗ giao nhau với đường sắt" },
        { kanji: "横断歩道", kana: "おうだんほどう", meaning: "Lối cho người qua đường" },
        { kanji: "一方通行", kana: "いっぽうつうこう", meaning: "Đường một chiều" },
        { kanji: "通行止め", kana: "つうこうどめ", meaning: "Cấm đi lại" },
        { kanji: "工事中", kana: "こうじちゅう", meaning: "Đang thi công" },
        { kanji: "駐車場", kana: "ちゅうしゃじょう", meaning: "Bãi đỗ xe" },
        { kanji: "シートベルト", kana: "シートベルト", meaning: "Dây an toàn" },
        { kanji: "スピード", kana: "スピード", meaning: "Tốc độ" },
        { kanji: "違反", kana: "いはん", meaning: "Vi phạm" },
        { kanji: "事故", kana: "じこ", meaning: "Tai nạn" },
        { kanji: "起こす", kana: "おこす", meaning: "Gây ra" },
        { kanji: "遭う", kana: "あう", meaning: "Gặp (tai nạn)" }
      ]
    },
    5: {
      title: "Lái xe ô tô (2)",
      japanese: "車に乗りましょう②",
      words: [
        { kanji: "ブレーキ", kana: "ブレーキ", meaning: "Phanh" },
        { kanji: "急ブレーキ", kana: "きゅうブレーキ", meaning: "Phanh gấp" },
        { kanji: "アクセル", kana: "アクセル", meaning: "Chân ga" },
        { kanji: "ハンドル", kana: "ハンドル", meaning: "Vô lăng" },
        { kanji: "ライト", kana: "ライト", meaning: "Đèn xe" },
        { kanji: "ワイパー", kana: "ワイパー", meaning: "Cần gạt nước" },
        { kanji: "ガソリン", kana: "ガソリン", meaning: "Xăng" },
        { kanji: "ガソリンスタンド", kana: "ガソリンスタンド", meaning: "Trạm xăng" },
        { kanji: "エンジン", kana: "エンジン", meaning: "Động cơ" },
        { kanji: "タイヤ", kana: "タイヤ", meaning: "Lốp xe" },
        { kanji: "パンクする", kana: "パンクする", meaning: "Thủng lốp" },
        { kanji: "バックミラー", kana: "バックミラー", meaning: "Gương chiếu hậu" },
        { kanji: "トランク", kana: "トランク", meaning: "Cốp xe" },
        { kanji: "バックする", kana: "バックする", meaning: "Lùi xe" },
        { kanji: "止める", kana: "とめる", meaning: "Dừng xe (tự động, đỗ xe)" },
        { kanji: "止まる", kana: "とまる", meaning: "Xe dừng lại" },
        { kanji: "乗せる", kana: "のせる", meaning: "Cho lên xe" },
        { kanji: "急に", kana: "きゅうに", meaning: "Đột ngột" },
        { kanji: "カーブ", kana: "カーブ", meaning: "Khúc cua" },
        { kanji: "曲がる", kana: "まがる", meaning: "Rẽ, quẹo" },
        { kanji: "気を付ける", kana: "きをつける", meaning: "Chú ý, cẩn thận" },
        { kanji: "注意する", kana: "ちゅういする", meaning: "Chú ý" },
        { kanji: "ぶつかる", kana: "ぶつかる", meaning: "Va chạm" },
        { kanji: "ぶつける", kana: "ぶつける", meaning: "Húc vào, va vào" },
        { kanji: "免許証", kana: "めんきょしょう", meaning: "Giấy phép lái xe" }
      ]
    },
    6: {
      title: "Giải quyết việc cá nhân",
      japanese: "用事を済ませましょう",
      words: [
        { kanji: "銀行", kana: "ぎんこう", meaning: "Ngân hàng" },
        { kanji: "口座", kana: "こうざ", meaning: "Tài khoản" },
        { kanji: "キャッシュカード", kana: "キャッシュカード", meaning: "Thẻ rút tiền mặt" },
        { kanji: "現金", kana: "げんきん", meaning: "Tiền mặt" },
        { kanji: "お札", kana: "おさつ", meaning: "Tiền giấy" },
        { kanji: "硬貨", kana: "こうか", meaning: "Tiền xu" },
        { kanji: "小銭", kana: "こぜに", meaning: "Tiền lẻ" },
        { kanji: "崩す", kana: "くずす", meaning: "Phá tiền, đổi tiền lẻ" },
        { kanji: "預金する", kana: "よきんする", meaning: "Gửi tiền tiết kiệm" },
        { kanji: "預ける", kana: "あずける", meaning: "Gửi tiền, giao phó" },
        { kanji: "引き出す", kana: "ひきだす", meaning: "Rút tiền" },
        { kanji: "下ろす", kana: "おろす", meaning: "Rút tiền" },
        { kanji: "振り込む", kana: "ふりこむ", meaning: "Chuyển khoản" },
        { kanji: "送金する", kana: "そうきんする", meaning: "Gửi tiền" },
        { kanji: "手数料", kana: "てすうりょう", meaning: "Phí dịch vụ" },
        { kanji: "通帳", kana: "つうちょう", meaning: "Sổ tiết kiệm" },
        { kanji: "郵便局", kana: "ゆうびんきょく", meaning: "Bưu điện" },
        { kanji: "手紙", kana: "てがみ", meaning: "Bức thư" },
        { kanji: "小包", kana: "こづつみ", meaning: "Bưu kiện nhỏ" },
        { kanji: "速達", kana: "そくたつ", meaning: "Chuyển phát nhanh" },
        { kanji: "書留", kana: "かきとめ", meaning: "Thư bảo đảm" },
        { kanji: "宛名", kana: "あてな", meaning: "Tên và địa chỉ người nhận" },
        { kanji: "差出人", kana: "さしだしにん", meaning: "Người gửi" },
        { kanji: "ポスト", kana: "ポスト", meaning: "Hòm thư" },
        { kanji: "郵便番号", kana: "ゆうびんばんごう", meaning: "Mã bưu điện" }
      ]
    }
  }
};
