export const tryN3Data = {
  title: "Từ vựng Try! N3",
  japanese: "Try! 日本語能力試験 N3 語彙",
  words: [
    { kanji: "テレビ局", kana: "テレビきょく", meaning: "đài truyền hình" },
    { kanji: "性能", kana: "せいのう", meaning: "tính năng" },
    { kanji: "箱", kana: "はこ", meaning: "cái hộp" },
    { kanji: "気がつく", kana: "きがつく", meaning: "chú ý, để ý" },
    { kanji: "けわしい", kana: "けわしい", meaning: "hiểm trở" },
    { kanji: "薄い", kana: "うすい", meaning: "lạt, lỏng, mong manh" },
    { kanji: "電話に出る", kana: "でんわにでる", meaning: "nghe điện thoại, bắt máy" },
    { kanji: "酸素缶", kana: "さんそかん", meaning: "bình dưỡng khí" },
    { kanji: "双子", kana: "ふたご", meaning: "con sinh đôi" },
    { kanji: "目が回る", kana: "めがまわる", meaning: "hoa mắt, chóng mặt" },
    { kanji: "混む", kana: "こむ", meaning: "đông đúc" },
    { kanji: "悔しい", kana: "くやしい", meaning: "đáng tiếc, ân hận" },
    { kanji: "飛び乗る", kana: "とびのる", meaning: "nhảy lên" },
    { kanji: "工場", kana: "こうじょう", meaning: "nhà máy, công xưởng" },
    { kanji: "専門家", kana: "せんもんか", meaning: "chuyên gia" },
    { kanji: "お腹", kana: "おなか", meaning: "bụng" },
    { kanji: "痛い", kana: "いたい", meaning: "đau, nhức" },
    { kanji: "渡り鳥", kana: "わたりどり", meaning: "chim di cư, chim di trú" },
    { kanji: "単語", kana: "たんご", meaning: "từ vựng" },
    { kanji: "身分証明書", kana: "みぶんしょうめいしょ", meaning: "căn cước, chứng minh thư, giấy tờ tùy thân" },
    { kanji: "環境調査", kana: "かんきょうちょうさ", meaning: "nghiên cứu môi trường" },
    { kanji: "伝統文化", kana: "でんとうぶんか", meaning: "văn hóa truyền thống" },
    { kanji: "我々", kana: "われわれ", meaning: "chúng tôi, chúng ta" },
    { kanji: "画面", kana: "がめん", meaning: "màn hình" },
    { kanji: "伝統", kana: "でんとう", meaning: "truyền thống" },
    { kanji: "論文", kana: "ろんぶん", meaning: "luận văn" },
    { kanji: "調べる", kana: "しらべる", meaning: "nghiên cứu" },
    { kanji: "資料", kana: "しりょう", meaning: "tài liệu" },
    { kanji: "宝くじ", kana: "たからくじ", meaning: "vé số, xổ số" },
    { kanji: "驚く", kana: "おどろく", meaning: "ngạc nhiên, giật mình" },
    { kanji: "あきらめる", kana: "あきらめる", meaning: "bỏ cuộc" },
    { kanji: "登場人物", kana: "とうじょうじんぶつ", meaning: "nhân vật (trong tiểu thuyết, kịch, phim...)" },
    { kanji: "海外研修", kana: "かいがいけんしゅう", meaning: "đào tạo ở nước ngoài" },
    { kanji: "原稿", kana: "げんこう", meaning: "bản nháp, bản thảo" },
    { kanji: "普通", kana: "ふつう", meaning: "thông thường" },
    { kanji: "成績", kana: "せいせき", meaning: "thành tích" },
    { kanji: "暖房", kana: "だんぼう", meaning: "máy sưởi" },
    { kanji: "面倒", kana: "めんどう", meaning: "phiền hà, quấy rầy; khó khăn, trở ngại" },
    { kanji: "真似する", kana: "まねする", meaning: "bắt chước" },
    { kanji: "エサをあげる", kana: "えさをあげる", meaning: "cho ăn" },
    { kanji: "ハト", kana: "はと", meaning: "chim bồ câu" },
    { kanji: "盛大", kana: "せいだい", meaning: "hoành tráng, long trọng" },
    { kanji: "拍手", kana: "はくしゅ", meaning: "vỗ tay" },
    { kanji: "画像ファイル", kana: "가ぞうファイル", meaning: "file hình ảnh" },
    { kanji: "保存", kana: "ほぞn", meaning: "bảo tồn, bảo quản, lưu trữ" },
    { kanji: "雨宿り", kana: "あまやどり", meaning: "trú mưa" },
    { kanji: "夢中", kana: "むちゅう", meaning: "say sưa, say mê, miệt mài" },
    { kanji: "観客", kana: "かんきゃく", meaning: "khán giả, quan khách" },
    { kanji: "鳴る", kana: "なる", meaning: "gáy, reo, vang lên" },
    { kanji: "一人暮らし", kana: "ひとりぐらし", meaning: "sống một mình" },
    { kanji: "必ず", kana: "かならず", meaning: "nhất định, nhất quyết" },
    { kanji: "俳優", kana: "はいゆう", meaning: "diễn viên, nghệ sĩ" },
    { kanji: "舞台", kana: "ぶたい", meaning: "sân khấu, vũ đài" },
    { kanji: "政治", kana: "せいじ", meaning: "chính trị" },
    { kanji: "経済", kana: "けいざい", meaning: "nền kinh tế" },
    { kanji: "登場", kana: "とうじょう", meaning: "lối vào; sự xuất hiện, tung ra" },
    { kanji: "困る", kana: "こまる", meaning: "khó khăn, rắc rối; bối rối" },
    { kanji: "日課", kana: "にっか", meaning: "bài học hàng ngày" },
    { kanji: "ひも", kana: "ひも", meaning: "sợi dây" },
    { kanji: "嬉しい", kana: "うれしい", meaning: "vui sướng, hạnh phúc" },
    { kanji: "玄関", kana: "げんかん", meaning: "khu vực cửa ra vào" },
    { kanji: "全速力", kana: "ぜんそくりょく", meaning: "toàn bộ tốc lực" }
  ]
};
