export const lesson2Data = {
  title: "Bài 2: Động từ (99 từ)",
  japanese: "第2課: 動詞",
  words: [
    { kanji: "渇く", kana: "かわく", meaning: "khát" },
    { kanji: "嗅ぐ", kana: "かぐ", meaning: "ngửi" },
    { kanji: "叩く", kana: "たたく", meaning: "đánh, vỗ" },
    { kanji: "殴る", kana: "なぐる", meaning: "đấm" },
    { kanji: "ける", kana: "ける", meaning: "đá" },
    { kanji: "抱く", kana: "だく", meaning: "ôm" },
    { kanji: "倒れる", kana: "たおれる", meaning: "đổ" },
    { kanji: "倒す", kana: "たおす", meaning: "làm đổ" },
    { kanji: "起きる", kana: "おきる", meaning: "thức dậy" },
    { kanji: "起こす", kana: "おこす", meaning: "đánh thức" },
    { kanji: "尋ねる", kana: "たずねる", meaning: "hỏi" },
    { kanji: "呼ぶ", kana: "よぶ", meaning: "gọi" },
    { kanji: "叫ぶ", kana: "さけぶ", meaning: "gào to" },
    { kanji: "黙る", kana: "だまる", meaning: "im lặng" },
    { kanji: "飼う", kana: "かう", meaning: "nuôi" },
    { kanji: "数える", kana: "かぞえる", meaning: "đếm" },
    { kanji: "乾く", kana: "かわく", meaning: "khô" },
    { kanji: "乾かす", kana: "かわかす", meaning: "làm khô" },
    { kanji: "畳む", kana: "たたむ", meaning: "gấp" },
    { kanji: "誘う", kana: "さそう", meaning: "mời, rủ" },
    { kanji: "おごる", kana: "おごる", meaning: "chiêu đãi" },
    { kanji: "預かる", kana: "あずかる", meaning: "chăm sóc" },
    { kanji: "預ける", kana: "あずける", meaning: "gửi" },
    { kanji: "決まる", kana: "きまる", meaning: "được quyết định" },
    { kanji: "決める", kana: "きめる", meaning: "quyết định" },
    { kanji: "写る", kana: "うつる", meaning: "chụp được" },
    { kanji: "写す", kana: "うつす", meaning: "chụp" },
    { kanji: "思い出す", kana: "おもいだす", meaning: "nhớ lại" },
    { kanji: "教わる", kana: "おそわる", meaning: "được dạy" },
    { kanji: "申し込む", kana: "もうしこむ", meaning: "đăng ký" },
    { kanji: "断る", kana: "ことわる", meaning: "từ chối" },
    { kanji: "見つかる", kana: "みつかる", meaning: "được tìm thấy" },
    { kanji: "見つける", kana: "みつける", meaning: "tìm thấy" },
    { kanji: "捕まる", kana: "つかまる", meaning: "bị bắt" },
    { kanji: "捕まえる", kana: "つかまえる", meaning: "bắt" },
    { kanji: "乗る", kana: "のる", meaning: "leo lên" },
    { kanji: "乗せる", kana: "のせる", meaning: "cho lên" },
    { kanji: "降りる", kana: "おりる", meaning: "xuống" },
    { kanji: "降ろす", kana: "おろす", meaning: "cho xuống" },
    { kanji: "直る", kana: "なおる", meaning: "được sửa" },
    { kanji: "直す", kana: "なおす", meaning: "sửa" },
    { kanji: "治る", kana: "なおる", meaning: "hồi phục" },
    { kanji: "治す", kana: "なおす", meaning: "cứu chữa" },
    { kanji: "亡くなる", kana: "なくなる", meaning: "chết" },
    { kanji: "亡くす", kana: "なくす", meaning: "mất" },
    { kanji: "生まれる", kana: "うまれる", meaning: "được sinh ra" },
    { kanji: "生む", kana: "うむ", meaning: "sinh" },
    { kanji: "出会う", kana: "であう", meaning: "gặp ngẫu nhiên" },
    { kanji: "訪ねる", kana: "たずねる", meaning: "thăm" },
    { kanji: "付き合う", kana: "つきあう", meaning: "hẹn hò, giao tiếp" },
    { kanji: "効く", kana: "きく", meaning: "có hiệu quả" },
    { kanji: "はやる", kana: "はやる", meaning: "phổ biến" },
    { kanji: "経つ", kana: "たつ", meaning: "qua" },
    { kanji: "間に合う", kana: "まにあう", meaning: "làm cho kịp giờ" },
    { kanji: "間に合わせる", kana: "まにあわせる", meaning: "kịp giờ" },
    { kanji: "通う", kana: "かよう", meaning: "đi làm, học" },
    { kanji: "込む", kana: "こむ", meaning: "đông" },
    { kanji: "すれ違う", kana: "すれちがう", meaning: "vượt, lướt qua" },
    { kanji: "掛かる", kana: "かかる", meaning: "được bao phủ" },
    { kanji: "掛ける", kana: "かける", meaning: "bao phủ" },
    { kanji: "動く", kana: "うごく", meaning: "hoạt động" },
    { kanji: "動かす", kana: "うごかす", meaning: "di chuyển" },
    { kanji: "離れる", kana: "はなれる", meaning: "tránh xa" },
    { kanji: "離す", kana: "はなす", meaning: "tách ra" },
    { kanji: "ぶつかる", kana: "ぶつかる", meaning: "bị đâm" },
    { kanji: "ぶつける", kana: "ぶつける", meaning: "đâm" },
    { kanji: "こぼれる", kana: "こぼれる", meaning: "bị tràn" },
    { kanji: "こぼす", kana: "こぼす", meaning: "làm tràn" },
    { kanji: "ふく", kana: "ふく", meaning: "lau" },
    { kanji: "片付く", kana: "かたづく", meaning: "được dọn dẹp" },
    { kanji: "片付ける", kana: "かたづける", meaning: "dọn dẹp" },
    { kanji: "包む", kana: "つつむ", meaning: "bọc" },
    { kanji: "張る", kana: "はる", meaning: "dán" },
    { kanji: "無くなる", kana: "なくなる", meaning: "bị mất" },
    { kanji: "無くす", kana: "なくす", meaning: "làm mất" },
    { kanji: "足りる", kana: "たりる", meaning: "đủ" },
    { kanji: "残る", kana: "のこる", meaning: "bị thừa" },
    { kanji: "残す", kana: "のこす", meaning: "thừa" },
    { kanji: "腐る", kana: "くさる", meaning: "thối" },
    { kanji: "むける", kana: "むける", meaning: "bị lột" },
    { kanji: "むく", kana: "むく", meaning: "lột" },
    { kanji: "滑る", kana: "すべる", meaning: "trượt" },
    { kanji: "積もる", kana: "つもる", meaning: "được tích tụ" },
    { kanji: "積む", kana: "つむ", meaning: "tích tụ, chất lại" },
    { kanji: "空く", kana: "あく", meaning: "bị thủng, trống" },
    { kanji: "空ける", kana: "あける", meaning: "làm trống, thủng" },
    { kanji: "下がる", kana: "さがる", meaning: "bị giảm" },
    { kanji: "下げる", kana: "さげる", meaning: "giảm" },
    { kanji: "冷える", kana: "ひえる", meaning: "bị lạnh" },
    { kanji: "冷やす", kana: "ひやす", meaning: "làm lạnh" },
    { kanji: "冷める", kana: "さめる", meaning: "bị nguội" },
    { kanji: "冷ます", kana: "さます", meaning: "làm nguội" },
    { kanji: "燃える", kana: "もえる", meaning: "cháy" },
    { kanji: "燃やす", kana: "もやす", meaning: "đốt" },
    { kanji: "沸く", kana: "わく", meaning: "sôi" },
    { kanji: "沸かす", kana: "わかす", meaning: "đun sôi" },
    { kanji: "鳴る", kana: "なる", meaning: "kêu" },
    { kanji: "鳴らす", kana: "ならす", meaning: "làm kêu" },
    { kanji: "役立つ", kana: "やくだつ", meaning: "hữu ích" },
    { kanji: "役立てる", kana: "やくだてる", meaning: "được sử dụng" }
  ]
};
