export const lesson1Data = {
  title: "Bài 1: Danh từ (120 từ)",
  japanese: "第1課: 名詞",
  words: [
    { kanji: "男性", kana: "だんせい", meaning: "đàn ông" },
    { kanji: "女性", kana: "じょせい", meaning: "phụ nữ" },
    { kanji: "高齢", kana: "こうれい", meaning: "cao tuổi" },
    { kanji: "年上", kana: "としうえ", meaning: "hơn tuổi" },
    { kanji: "目上", kana: "めうえ", meaning: "bề trên" },
    { kanji: "先輩", kana: "せんぱい", meaning: "tiền bối" },
    { kanji: "後輩", kana: "こうはい", meaning: "hậu bối" },
    { kanji: "上司", kana: "じょうし", meaning: "cấp trên" },
    { kanji: "相手", kana: "あいて", meaning: "đối phương, người đối diện" },
    { kanji: "知り合い", kana: "しりあい", meaning: "người quen" },
    { kanji: "友人", kana: "ゆうじん", meaning: "bạn bè" },
    { kanji: "仲", kana: "なか", meaning: "mối quan hệ" },
    { kanji: "生年月日", kana: "せいねんがっぴ", meaning: "ngày tháng năm sinh" },
    { kanji: "誕生", kana: "たんじょう", meaning: "sự ra đời" },
    { kanji: "年", kana: "とし", meaning: "năm, tuổi" },
    { kanji: "出身", kana: "しゅっしん", meaning: "quê quán" },
    { kanji: "故郷", kana: "こきょう", meaning: "quê hương" },
    { kanji: "成長", kana: "せいちょう", meaning: "trưởng thành" },
    { kanji: "成人", kana: "せいじん", meaning: "người trưởng thành" },
    { kanji: "合格", kana: "ごうかく", meaning: "thi đỗ" },
    { kanji: "進学", kana: "しんがく", meaning: "học lên cao" },
    { kanji: "退学", kana: "たいがく", meaning: "bỏ học" },
    { kanji: "就職", kana: "しゅうしょく", meaning: "tìm việc làm" },
    { kanji: "退職", kana: "たいしょく", meaning: "nghỉ việc" },
    { kanji: "失業", kana: "しつぎょう", meaning: "thất nghiệp" },
    { kanji: "残業", kana: "ざんぎょう", meaning: "làm thêm giờ" },
    { kanji: "生活", kana: "せいかつ", meaning: "cuộc sống" },
    { kanji: "通勤", kana: "つうきん", meaning: "đi làm" },
    { kanji: "学歴", kana: "がくれき", meaning: "bằng cấp" },
    { kanji: "給料", kana: "きゅうりょう", meaning: "tiền lương" },
    { kanji: "面接", kana: "めんせつ", meaning: "phỏng vấn" },
    { kanji: "休憩", kana: "きゅうけい", meaning: "nghỉ ngơi" },
    { kanji: "観光", kana: "かんこう", meaning: "tham quan" },
    { kanji: "帰国", kana: "きこく", meaning: "về nước" },
    { kanji: "帰省", kana: "きせい", meaning: "về quê" },
    { kanji: "帰宅", kana: "きたく", meaning: "về nhà" },
    { kanji: "参加", kana: "さんか", meaning: "tham gia" },
    { kanji: "出席", kana: "しゅっせき", meaning: "có mặt" },
    { kanji: "欠席", kana: "けっせき", meaning: "vắng mặt" },
    { kanji: "遅刻", kana: "ちこく", meaning: "đến muộn" },
    { kanji: "化粧", kana: "けしょう", meaning: "trang điểm" },
    { kanji: "計算", kana: "けいさん", meaning: "tính toán" },
    { kanji: "計画", kana: "けいかく", meaning: "kế hoạch" },
    { kanji: "成功", kana: "せいこう", meaning: "thành công" },
    { kanji: "失敗", kana: "しっぱい", meaning: "thất bại" },
    { kanji: "準備", kana: "じゅんび", meaning: "chuẩn bị" },
    { kanji: "整理", kana: "せいり", meaning: "chỉnh sửa, sắp xếp" },
    { kanji: "注文", kana: "ちゅうもん", meaning: "đặt hàng" },
    { kanji: "貯金", kana: "ちょきん", meaning: "tiết kiệm tiền" },
    { kanji: "徹夜", kana: "てつや", meaning: "thức trắng đêm" },
    { kanji: "引っ越し", kana: "ひっこし", meaning: "chuyển nhà" },
    { kanji: "身長", kana: "しんちょう", meaning: "chiều cao" },
    { kanji: "体重", kana: "たいじゅう", meaning: "cân nặng" },
    { kanji: "けが", kana: "けが", meaning: "vết thương" },
    { kanji: "会", kana: "かい", meaning: "hội, tiệc" },
    { kanji: "趣味", kana: "しゅみ", meaning: "sở thích" },
    { kanji: "興味", kana: "きょうみ", meaning: "hứng thú" },
    { kanji: "思い出", kana: "おもいで", meaning: "kỷ niệm, nhớ lại" },
    { kanji: "冗談", kana: "じょうだん", meaning: "đùa cợt" },
    { kanji: "目的", kana: "もくてき", meaning: "mục đích" },
    { kanji: "約束", kana: "やくそく", meaning: "lời hứa" },
    { kanji: "おしゃべり", kana: "おしゃべり", meaning: "tán gẫu, nói chuyện riêng" },
    { kanji: "遠慮", kana: "えんりょ", meaning: "ngại ngần, khách sáo" },
    { kanji: "我慢", kana: "がまん", meaning: "chịu đựng" },
    { kanji: "迷惑", kana: "めいわく", meaning: "làm phiền" },
    { kanji: "希望", kana: "きぼう", meaning: "hi vọng" },
    { kanji: "夢", kana: "ゆめ", meaning: "giấc mơ" },
    { kanji: "賛成", kana: "さんせい", meaning: "đồng ý" },
    { kanji: "反対", kana: "はんたい", meaning: "đối lập, phản đối" },
    { kanji: "想像", kana: "そうぞう", meaning: "tưởng tượng" },
    { kanji: "努力", kana: "どりょく", meaning: "nỗ lực" },
    { kanji: "太陽", kana: "たいよう", meaning: "mặt trời" },
    { kanji: "地球", kana: "ちきゅう", meaning: "trái đất" },
    { kanji: "温度", kana: "おんど", meaning: "nhiệt độ" },
    { kanji: "湿度", kana: "しつど", meaning: "độ ẩm" },
    { kanji: "湿気", kana: "しっけ", meaning: "hơi ẩm" },
    { kanji: "梅雨", kana: "つゆ", meaning: "mùa mưa" },
    { kanji: "かび", kana: "かび", meaning: "nấm mốc" },
    { kanji: "暖房", kana: "だんぼう", meaning: "máy sưởi, điều hòa ấm" },
    { kanji: "皮", kana: "かわ", meaning: "da, vỏ" },
    { kanji: "缶", kana: "かん", meaning: "lon, đồ hộp" },
    { kanji: "画面", kana: "がめん", meaning: "màn hình" },
    { kanji: "番組", kana: "ばんぐみ", meaning: "chương trình" },
    { kanji: "記事", kana: "きじ", meaning: "ký sự, bài báo" },
    { kanji: "近所", kana: "きんじょ", meaning: "hàng xóm, xung quanh" },
    { kanji: "警察", kana: "けいさつ", meaning: "cảnh sát" },
    { kanji: "犯人", kana: "はんにん", meaning: "tội phạm" },
    { kanji: "小銭", kana: "こぜに", meaning: "tiền lẻ" },
    { kanji: "ごちそう", kana: "ごちそう", meaning: "chiêu đãi" },
    { kanji: "作者", kana: "さくしゃ", meaning: "tác giả" },
    { kanji: "作品", kana: "さくひん", meaning: "tác phẩm" },
    { kanji: "制服", kana: "せいふく", meaning: "đồng phục" },
    { kanji: "洗剤", kana: "せんざい", meaning: "bột giặt, chất tẩy rửa" },
    { kanji: "底", kana: "そこ", meaning: "đáy" },
    { kanji: "地下", kana: "ちか", meaning: "ngầm, dưới đất" },
    { kanji: "寺", kana: "てら", meaning: "chùa" },
    { kanji: "道路", kana: "どうろ", meaning: "đường xá" },
    { kanji: "坂", kana: "さか", meaning: "dốc" },
    { kanji: "煙", kana: "けむり", meaning: "khói" },
    { kanji: "灰", kana: "はい", meaning: "tàn, tro" },
    { kanji: "判", kana: "はん", meaning: "con dấu" },
    { kanji: "名刺", kana: "めいし", meaning: "danh thiếp" },
    { kanji: "免許", kana: "めんきょ", meaning: "giấy phép" },
    { kanji: "多く", kana: "おおく", meaning: "nhiều" },
    { kanji: "前半", kana: "ぜんはん", meaning: "phần đầu" },
    { kanji: "後半", kana: "こうはん", meaning: "phần cuối" },
    { kanji: "最高", kana: "さいこう", meaning: "cao nhất" },
    { kanji: "最低", kana: "さいてい", meaning: "thấp nhất" },
    { kanji: "最初", kana: "さいしょ", meaning: "đầu tiên" },
    { kanji: "最後", kana: "さいご", meaning: "cuối cùng" },
    { kanji: "自動", kana: "じどう", meaning: "tự động" },
    { kanji: "種類", kana: "しゅるい", meaning: "loại, chủng loại" },
    { kanji: "性格", kana: "せいかく", meaning: "tính cách" },
    { kanji: "性質", kana: "せいしつ", meaning: "tính chất" },
    { kanji: "順番", kana: "じゅんばん", meaning: "thứ tự" },
    { kanji: "番", kana: "ばん", meaning: "lượt" },
    { kanji: "方法", kana: "ほうほう", meaning: "phương pháp" },
    { kanji: "製品", kana: "せいひん", meaning: "sản phẩm" },
    { kanji: "値上がり", kana: "ねあがり", meaning: "tăng giá" },
    { kanji: "生", kana: "なま", meaning: "tươi, sống" }
  ]
};
