export const lesson12Data = {
  title: "Bài 12: Phó từ & Từ nối (35 từ)",
  japanese: "第12課: 副詞 & 接続詞",
  words: [
    { kanji: "ぐっすり", kana: "ぐっすり", meaning: "say" },
    { kanji: "きちんと", kana: "きちんと", meaning: "ngay ngắn" },
    { kanji: "しっかり", kana: "しっかり", meaning: "kiên quyết, chắc chắn, đáng tin cậy" },
    { kanji: "はっきり", kana: "はっきり", meaning: "rõ ràng" },
    { kanji: "じっと", kana: "じっと", meaning: "kiên nhẫn, chăm chú, chằm chằm" },
    { kanji: "そっと", kana: "そっと", meaning: "nhẹ nhàng, yên lặng" },
    { kanji: "別々に", kana: "べつべつに", meaning: "riêng biệt" },
    { kanji: "それぞれ", kana: "それぞれ", meaning: "lần lượt, tương ứng" },
    { kanji: "互いに", kana: "たがいに", meaning: "lẫn nhau" },
    { kanji: "直接", kana: "ちょくせつ", meaning: "trực tiếp" },
    { kanji: "本当に", kana: "ほんとうに", meaning: "thật lòng, kỳ thực" },
    { kanji: "必ず", kana: "かならず", meaning: "chắc chắn" },
    { kanji: "絶対に", kana: "ぜったいに", meaning: "chắc chắn rồi" },
    { kanji: "特に", kana: "とくに", meaning: "đặc biệt là" },
    { kanji: "ただ", kana: "ただ", meaning: "chỉ" },
    { kanji: "少なくとも", kana: "すくなくとも", meaning: "ít nhất" },
    { kanji: "決して", kana: "けっして", meaning: "không bao giờ" },
    { kanji: "少しも", kana: "すこしも", meaning: "một chút" },
    { kanji: "ちっとも", kana: "ちっとも", meaning: "(không) tí gì" },
    { kanji: "全く", kana: "まったく", meaning: "hoàn toàn (không)" },
    { kanji: "とても", kana: "とても", meaning: "rất" },
    { kanji: "どんなに", kana: "どんなに", meaning: "thế nào, bao nhiêu" },
    { kanji: "どうしても", kana: "どうしても", meaning: "kiểu gì cũng" },
    { kanji: "まるで", kana: "まるで", meaning: "như là" },
    { kanji: "一体", kana: "いったい", meaning: "cái quái gì" },
    { kanji: "別に", kana: "べつに", meaning: "(không) có gì" },
    { kanji: "たった", kana: "たった", meaning: "chỉ" },
    { kanji: "ほんの", kana: "ほんの", meaning: "một chút" },
    { kanji: "それで", kana: "それで", meaning: "thế thì" },
    { kanji: "そこで", kana: "そこで", meaning: "tiếp theo" },
    { kanji: "そのうえ", kana: "そのうえ", meaning: "hơn nữa" },
    { kanji: "また", kana: "また", meaning: "nữa" },
    { kanji: "または", kana: "または", meaning: "hoặc" },
    { kanji: "それとも", kana: "それとも", meaning: "hoặc" },
    { kanji: "つまり", kana: "つまり", meaning: "nói cách khác" }
  ]
};
