export const lesson9Data = {
  title: "Bài 9: Danh từ C (80 từ)",
  japanese: "第9課: 名詞Ｃ",
  words: [
    { kanji: "読書", kana: "どくしょ", meaning: "đọc viết" },
    { kanji: "演奏", kana: "えんそう", meaning: "biểu diễn" },
    { kanji: "芸術", kana: "げいじゅつ", meaning: "nghệ thuật" },
    { kanji: "検査", kana: "けんさ", meaning: "kiểm tra" },
    { kanji: "血液", kana: "けつえき", meaning: "máu" },
    { kanji: "治療", kana: "ちりょう", meaning: "trị liệu" },
    { kanji: "症状", kana: "しょうじょう", meaning: "triệu chứng" },
    { kanji: "予防", kana: "よぼう", meaning: "dự phòng" },
    { kanji: "栄養", kana: "えいよう", meaning: "dinh dưỡng" },
    { kanji: "手術", kana: "しゅうじゅつ", meaning: "phẫu thuật" },
    { kanji: "死亡", kana: "しぼう", meaning: "tử vong" },
    { kanji: "命", kana: "いのち", meaning: "sinh mạng" },
    { kanji: "一生", kana: "いっしょう", meaning: "suốt đời" },
    { kanji: "誤解", kana: "ごかい", meaning: "hiểu nhầm" },
    { kanji: "後悔", kana: "こうかい", meaning: "hối hận" },
    { kanji: "訳", kana: "わけ", meaning: "lý do" },
    { kanji: "態度", kana: "たいど", meaning: "thái độ" },
    { kanji: "癖", kana: "くせ", meaning: "thói quen" },
    { kanji: "礼儀", kana: "れいぎ", meaning: "lễ nghĩa" },
    { kanji: "文句", kana: "もんく", meaning: "phàn nàn" },
    { kanji: "表情", kana: "ひょうじょう", meaning: "biểu lộ, biểu thị" },
    { kanji: "鏡面", kana: "ひょうめん", meaning: "bề mặt" },
    { kanji: "禁煙", kana: "きんえん", meaning: "cấm hút thuốc" },
    { kanji: "禁止", kana: "きんし", meaning: "cấm" },
    { kanji: "完成", kana: "かんせい", meaning: "hoàn thành" },
    { kanji: "課題", kana: "かだい", meaning: "chủ đề" },
    { kanji: "例外", kana: "れいがい", meaning: "ngoại lệ" },
    { kanji: "基本", kana: "きほん", meaning: "cơ bản" },
    { kanji: "記録", kana: "きろく", meaning: "ghi âm" },
    { kanji: "状態", kana: "じょうたい", meaning: "trạng thái" },
    { kanji: "出来事", kana: "できごと", meaning: "sự kiện" },
    { kanji: "場面", kana: "ばめん", meaning: "khung cảnh, tình huống, hiện trường" },
    { kanji: "機会", kana: "きかい", meaning: "cơ hội" },
    { kanji: "距離", kana: "きょり", meaning: "khoảng cách" },
    { kanji: "提案", kana: "ていあん", meaning: "đề xuất" },
    { kanji: "やり取り", kana: "やりとり", meaning: "trao đổi, làm việc" },
    { kanji: "知識", kana: "ちしき", meaning: "kiến thức" },
    { kanji: "実力", kana: "じつりょく", meaning: "thực lực" },
    { kanji: "手段", kana: "しゅだん", meaning: "cách thức" },
    { kanji: "代表", kana: "だいひょう", meaning: "đại biểu" },
    { kanji: "影響", kana: "えいきょう", meaning: "ảnh hưởng" },
    { kanji: "効果", kana: "こうか", meaning: "hiệu quả" },
    { kanji: "印象", kana: "いんしょう", meaning: "ấn tượng" },
    { kanji: "印", kana: "しるし", meaning: "dấu, dấu hiệu" },
    { kanji: "合図", kana: "あいず", meaning: "ám hiệu" },
    { kanji: "共通", kana: "きょうつう", meaning: "chung" },
    { kanji: "協調", kana: "きょうちょう", meaning: "nhấn mạnh" },
    { kanji: "省略", kana: "しょうりゃく", meaning: "lược bớt" },
    { kanji: "挑戦", kana: "ちょうせん", meaning: "thử thách" },
    { kanji: "やる気", kana: "やるき", meaning: "động lực" },
    { kanji: "勇気", kana: "ゆうき", meaning: "dũng cảm, dũng khí" },
    { kanji: "資格", kana: "しかく", meaning: "bằng cấp, tư cách" },
    { kanji: "申請", kana: "しんせい", meaning: "đăng ký, ứng tuyển" },
    { kanji: "本人", kana: "ほんにん", meaning: "người được nói đến" },
    { kanji: "契約", kana: "けいやく", meaning: "hợp đồng" },
    { kanji: "証明", kana: "しょうめい", meaning: "chứng minh, bằng chứng" },
    { kanji: "変更", kana: "へんこう", meaning: "thay đổi" },
    { kanji: "保存", kana: "ほぞん", meaning: "bảo tồn" },
    { kanji: "保護", kana: "ほご", meaning: "bảo vệ" },
    { kanji: "環境", kana: "かんきょう", meaning: "môi trường" },
    { kanji: "資源", kana: "しげん", meaning: "tài nguyên" },
    { kanji: "不足", kana: "ふそく", meaning: "thiếu" },
    { kanji: "平均", kana: "へいきん", meaning: "trung bình" },
    { kanji: "割合", kana: "わりあい", meaning: "tỷ lệ" },
    { kanji: "商売", kana: "しょうばい", meaning: "kinh doanh, buôn bán" },
    { kanji: "商品", kana: "しょうひん", meaning: "sản phẩm" },
    { kanji: "質", kana: "しつ", meaning: "chất lượng" },
    { kanji: "型", kana: "かた", meaning: "mẫu" },
    { kanji: "生産", kana: "せいさん", meaning: "sản xuất" },
    { kanji: "消費", kana: "しょうひ", meaning: "tiêu dùng, tiêu thụ" },
    { kanji: "物価", kana: "ぶっか", meaning: "giá cả, vật giá" },
    { kanji: "倒産", kana: "とうさん", meaning: "phá sản" },
    { kanji: "携帯", kana: "けいたい", meaning: "mang theo" },
    { kanji: "現代", kana: "げんだい", meaning: "hiện tại" },
    { kanji: "世紀", kana: "せいき", meaning: "thế kỷ" },
    { kanji: "文化", kana: "ぶんか", meaning: "văn hóa" },
    { kanji: "都市", kana: "とし", meaning: "thành phố" },
    { kanji: "地方", kana: "ちほう", meaning: "địa phương" },
    { kanji: "戦争", kana: "せんそう", meaning: "chiến tranh" },
    { kanji: "平和", kana: "へいわ", meaning: "hòa bình" }
  ]
};
