export const lesson7Data = {
  title: "Bài 7: Tính từ B (40 từ)",
  japanese: "第7課: 形容詞Ｂ",
  words: [
    { kanji: "濃い", kana: "こい", meaning: "đậm, đặc" },
    { kanji: "薄い", kana: "うすい", meaning: "mỏng, nhạt" },
    { kanji: "酸っぱい", kana: "すっぱい", meaning: "chua" },
    { kanji: "臭い", kana: "くさい", meaning: "thối" },
    { kanji: "おかしい", kana: "おかしい", meaning: "lạ" },
    { kanji: "かっこいい", kana: "かっこいい", meaning: "bảnh bao" },
    { kanji: "うまい", kana: "うまい", meaning: "ngon" },
    { kanji: "親しい", kana: "したしい", meaning: "thân thiết" },
    { kanji: "詳しい", kana: "くわしい", meaning: "chi tiết" },
    { kanji: "細かい", kana: "こまかい", meaning: "tiểu tiết, bé" },
    { kanji: "浅い", kana: "あさい", meaning: "nông" },
    { kanji: "固い", kana: "かたい", accepts: ["硬い"], meaning: "cứng" },
    { kanji: "ぬるい", kana: "ぬるい", meaning: "nguội" },
    { kanji: "まぶしい", kana: "まぶしい", meaning: "chói" },
    { kanji: "蒸し暑い", kana: "むしあつい", meaning: "nóng ẩm" },
    { kanji: "清潔な", kana: "せいけつな", meaning: "sạch" },
    { kanji: "新鮮な", kana: "しんせんな", meaning: "tươi" },
    { kanji: "豊かな", kana: "ゆたかな", meaning: "giàu có" },
    { kanji: "立派な", kana: "りっぱな", meaning: "siêu" },
    { kanji: "正確な", kana: "せいけくな", meaning: "chính xác" },
    { kanji: "確かな", kana: "たしかな", meaning: "đích thực" },
    { kanji: "重要な", kana: "じゅうような", meaning: "quan trọng" },
    { kanji: "必要な", kana: "ひつような", meaning: "cần thiết" },
    { kanji: "もったいない", kana: "もったいない", meaning: "lãng phí" },
    { kanji: "すごい", kana: "すごい", meaning: "ghê, siêu" },
    { kanji: "ひどい", kana: "ひどい", meaning: "tồi" },
    { kanji: "激しい", kana: "はげしい", meaning: "mãnh liệt" },
    { kanji: "そっくりな", kana: "そっくりな", meaning: "giống" },
    { kanji: "急な", kana: "きゅうな", meaning: "đột nhiên" },
    { kanji: "適当な", kana: "てきとうな", meaning: "phù hợp" },
    { kanji: "特別な", kana: "とくべつな", meaning: "đặc biệt" },
    { kanji: "完全な", kana: "かんぜんな", meaning: "toàn bộ" },
    { kanji: "盛んな", kana: "さかんな", meaning: "thịnh vượng" },
    { kanji: "様々な", kana: "さまざまな", meaning: "đa dạng" },
    { kanji: "可能な", kana: "かのうな", meaning: "khả thi" },
    { kanji: "不可能な", kana: "ふかのうな", meaning: "bất khả thi" },
    { kanji: "基本的な", kana: "きほんてきな", meaning: "cơ bản" },
    { kanji: "国際的な", kana: "こくさいてきな", meaning: "tính quốc tế" },
    { kanji: "ばらばらな", kana: "ばらばらな", meaning: "tung tóe, chia rẽ" },
    { kanji: "ぼろぼろな", kana: "ぼろぼろな", meaning: "rách nát, te tua" }
  ]
};
