export const lesson10Data = {
  title: "Bài 10: Động từ C (80 từ)",
  japanese: "第10課: 動詞Ｃ",
  words: [
    { kanji: "上る", kana: "のぼる", meaning: "leo lên" },
    { kanji: "下る", kana: "くだる", meaning: "đi xuống" },
    { kanji: "進む", kana: "すすむ", meaning: "tiến lên" },
    { kanji: "進める", kana: "すすめる", meaning: "làm cho tiến lên" },
    { kanji: "通る", kana: "とおる", meaning: "thông qua, được chấp nhận, đi qua" },
    { kanji: "通す", kana: "とおす", meaning: "xuyên qua, thông qua" },
    { kanji: "超える・越える", kana: "こえる", meaning: "vượt qua" },
    { kanji: "過ぎる", kana: "すぎる", meaning: "quá, đi qua" },
    { kanji: "過ごす", kana: "すごす", meaning: "sử dụng(thời gian)" },
    { kanji: "移る", kana: "うつる", meaning: "được chuyển" },
    { kanji: "移す", kana: "うつす", meaning: "chuyển" },
    { kanji: "連れる", kana: "つれる", meaning: "dẫn đi" },
    { kanji: "寄る", kana: "よる", meaning: "ghé sát, lại gần" },
    { kanji: "寄せる", kana: "よせる", meaning: "ghé vào" },
    { kanji: "与える", kana: "あたえる", meaning: "trao, cung cấp" },
    { kanji: "得る", kana: "える", meaning: "đạt được, có được" },
    { kanji: "向く", kana: "むく", meaning: "hướng, đối diện" },
    { kanji: "向ける", kana: "むける", meaning: "hướng đến, quay" },
    { kanji: "勧める", kana: "すすめる", meaning: "rủ, mời, gợi ý" },
    { kanji: "薦める", kana: "すすめる", meaning: "giới thiệu, gợi ý" },
    { kanji: "任せる", kana: "まかせる", meaning: "tin tưởng, để cho ai đó làm gì" },
    { kanji: "守る", kana: "まもる", meaning: "giữ, tuân thủ, bảo vệ" },
    { kanji: "争う", kana: "あらそう", meaning: "gây gổ, tranh giành" },
    { kanji: "臨む", kana: "のぞむ", meaning: "ước" },
    { kanji: "信じる", kana: "しんじる", meaning: "tin tưởng" },
    { kanji: "通じる", kana: "つうじる", meaning: "hiểu, thông qua" },
    { kanji: "飽きる", kana: "あきる", meaning: "chán, ngấy" },
    { kanji: "思いつく", kana: "おもいつく", meaning: "nghĩ về" },
    { kanji: "思いやる", kana: "おもいやる", meaning: "quan tâm, thông cảm" },
    { kanji: "熱中する", kana: "ねっちゅうする", meaning: "nghiện" },
    { kanji: "暮らす", kana: "くらす", meaning: "sống" },
    { kanji: "巻く", kana: "まく", meaning: "quấn, quàng" },
    { kanji: "結ぶ", kana: "むすぶ", meaning: "buộc, cột, nối" },
    { kanji: "済む", kana: "すむ", meaning: "kết thúc" },
    { kanji: "済ませる・済ます", kana: "すませる・済ます", meaning: "hoàn tất" },
    { kanji: "出来る", kana: "できる", meaning: "có thể, được xây dựng" },
    { kanji: "切れる", kana: "きれる", meaning: "cắt, hết hạn" },
    { kanji: "切らす", kana: "きらす", meaning: "hết" },
    { kanji: "伝わる", kana: "つたわる", meaning: "được truyền đi, được trải ra, được giới thiệu" },
    { kanji: "伝える", kana: "つたえる", meaning: "truyền đi, giới thiệu" },
    { kanji: "続く", kana: "つづく", meaning: "tiếp tục, xảy ra, lặp lại, theo sau" },
    { kanji: "続ける", kana: "つづける", meaning: "tiếp tục, xảy ra liên tiếp" },
    { kanji: "つながる", kana: "つながる", meaning: "được kết nối, được mở rộng, thông qua" },
    { kanji: "つなぐ", kana: "つなぐ", meaning: "kết nối, tham gia" },
    { kanji: "つなげる", kana: "つなげる", meaning: "kết nối, làm chặt thêm" },
    { kanji: "伸びる", kana: "のびる", meaning: "lớn lên, tăng thêm, dài ra" },
    { kanji: "伸ばす", kana: "のばす", meaning: "nuôi dài, căng ra" },
    { kanji: "延びる", kana: "のびる", meaning: "bị trì hoãn, bị kéo dài" },
    { kanji: "延ばす", kana: "のばす", meaning: "trì hoãn, kéo dài" },
    { kanji: "重なる", kana: "かさなる", meaning: "xung đột, xếp chồng" },
    { kanji: "重ねる", kana: "かさねる", meaning: "chồng lên, tích trữ" },
    { kanji: "広がる", kana: "ひろがる", meaning: "mở rộng, bùng phát, lan tràn, trải dài" },
    { kanji: "広げる", kana: "ひろげる", meaning: "mở thêm, mở rộng, nới rộng, mở ra" },
    { kanji: "載る", kana: "のる", meaning: "vừa, được công bố" },
    { kanji: "載せる", kana: "のせる", meaning: "cho vào, cho lên, công bố" },
    { kanji: "そろう", kana: "そろう", meaning: "thu thập, được thu thập" },
    { kanji: "そろえる", kana: "そろえる", meaning: "gom lại, chuẩn bị sẵn sàng" },
    { kanji: "まとまる", kana: "まとまる", meaning: "được thống nhất, được tổ chức, được sắp xếp" },
    { kanji: "まとめる", kana: "まとめる", meaning: "tập hợp, sàng lọc, hợp nhất, tổ chức" },
    { kanji: "付く", kana: "つく", meaning: "dính, gắn, đạt được, đi cùng với" },
    { kanji: "付ける", kana: "つける", meaning: "gắn, thêm vào" },
    { kanji: "たまる", kana: "たまる", meaning: "được tiết kiệm" },
    { kanji: "ためる", kana: "ためる", meaning: "tiết kiệm" },
    { kanji: "交じる・混じる", kana: "まじる", meaning: "giao vào, lẫn vào" },
    { kanji: "交ざる・混ざる", kana: "まざる", meaning: "được trộn lẫn" },
    { kanji: "交ぜる・混ぜる", kana: "まぜる", meaning: "trộn vào" },
    { kanji: "解ける・溶ける", kana: "とける", meaning: "được giải quyết, nóng chảy" },
    { kanji: "解く・溶く", kana: "とく", meaning: "giải quyết, nóng chảy" },
    { kanji: "含む", kana: "ふくむ", meaning: "chứa, bao gồm" },
    { kanji: "含める", kana: "ふくめる", meaning: "bao gồm" },
    { kanji: "抜ける", kana: "ぬける", meaning: "tháo, tuột" },
    { kanji: "抜く", kana: "ぬく", meaning: "lấy ra" },
    { kanji: "現れる", kana: "あらわれる", meaning: "xuất hiện, được thẻ hiện" },
    { kanji: "現す", kana: "あらわす", meaning: "xuất hiện, hiện ra" },
    { kanji: "表れる", kana: "あらわれる", meaning: "biểu hiện (trên mặt)" },
    { kanji: "表す", kana: "あらわす", meaning: "biểu thị, biểu lộ, đại diện" },
    { kanji: "散る", kana: "ちる", meaning: "bị tàn, rụng" },
    { kanji: "散らす", kana: "ちらす", meaning: "tàn" },
    { kanji: "明ける", kana: "あける", meaning: "(đêm) đến, (năm mới) bắt đầu, (mùa mưa) kết thúc" },
    { kanji: "差す", kana: "さす", meaning: "(mặt trời) chiếu sáng, mở (ô), nhỏ (thuốc mắt)" }
  ]
};
