export const lesson11Data = {
  title: "Bài 11: Katakana B & Động từ (50 từ)",
  japanese: "第11課: カタカナＢ & 動詞",
  words: [
    { kanji: "パートナー", kana: "パートナー", meaning: "đối tác" },
    { kanji: "リーダー", kana: "リーダー", meaning: "lãnh đạo" },
    { kanji: "ボランティア", kana: "ボランティア", meaning: "tình nguyện" },
    { kanji: "コミュニケーション", kana: "コミュニケーション", meaning: "giao tiếp" },
    { kanji: "ユーモア", kana: "ユーモア", meaning: "hài hước, đùa" },
    { kanji: "ショック", kana: "ショック", meaning: "shock, choáng" },
    { kanji: "ストレス", kana: "ストレス", meaning: "căng thẳng, stress" },
    { kanji: "バランス", kana: "バランス", meaning: "cân bằng" },
    { kanji: "レベル", kana: "レベル", meaning: "trình độ, level" },
    { kanji: "アップ", kana: "アップ", meaning: "tăng lên" },
    { kanji: "ダウン", kana: "ダウン", meaning: "giảm xuống" },
    { kanji: "プラス", kana: "プラス", meaning: "phép cộng, tác động tích cực" },
    { kanji: "マイナス", kana: "マイナス", meaning: "phép trừ, tác động tiêu cực" },
    { kanji: "イメージ", kana: "イメージ", meaning: "hình ảnh" },
    { kanji: "コンテスト", kana: "コンテスト", meaning: "cuộc thi" },
    { kanji: "マスコミ", kana: "マスコミ", meaning: "thông tin truyền thông" },
    { kanji: "プライバシー", kana: "プライバシー", meaning: "cá nhân, riêng tư" },
    { kanji: "オフィス", kana: "オフィス", meaning: "văn phòng" },
    { kanji: "ルール", kana: "ルール", meaning: "luật lệ" },
    { kanji: "マナー", kana: "マナー", meaning: "kiểu, thói" },
    { kanji: "ミス", kana: "ミス", meaning: "lỗi" },
    { kanji: "スケジュール", kana: "スケジュール", meaning: "lịch, kế hoạch" },
    { kanji: "タイトル", kana: "タイトル", meaning: "tiêu đề" },
    { kanji: "テーマ", kana: "テーマ", meaning: "chủ đề" },
    { kanji: "ストーリー", kana: "ストーリー", meaning: "câu chuyện" },
    { kanji: "ヒット", kana: "ヒット", meaning: "nổi tiếng" },
    { kanji: "ブランド", kana: "ブランド", meaning: "nhãn hiệu" },
    { kanji: "レンタル", kana: "レンタル", meaning: "thuê" },
    { kanji: "リサイクル", kana: "リサイクル", meaning: "tái chế" },
    { kanji: "ラベル", kana: "ラベル", meaning: "nhãn" },
    { kanji: "タイプ", kana: "タイプ", meaning: "loại" },
    { kanji: "スタイル", kana: "スタイル", meaning: "kiểu dáng" },
    { kanji: "セット", kana: "セット", meaning: "cài đặt, set" },
    { kanji: "ウイルス", kana: "ウイルス", meaning: "virus" },
    { kanji: "ロボット", kana: "ロボット", meaning: "robot" },
    { kanji: "エネルギー", kana: "エネルギー", meaning: "năng lượng" },
    { kanji: "デジタル", kana: "デジタル", meaning: "kỹ thuật số" },
    { kanji: "マイク", kana: "マイク", meaning: "microphone, ghi âm" },
    { kanji: "ブレーキ", kana: "ブレーキ", meaning: "phanh" },
    { kanji: "ペンキ", kana: "ペンキ", meaning: "sơn" },
    { kanji: "炊ける", kana: "たける", meaning: "được nấu" },
    { kanji: "炊く", kana: "たく", meaning: "nấu" },
    { kanji: "煮える", kana: "にえる", meaning: "được nấu, được ninh" },
    { kanji: "煮る", kana: "にる", meaning: "nấu, ninh, luộc" },
    { kanji: "炒める", kana: "いためる", meaning: "rán" },
    { kanji: "焼ける", kana: "やける", meaning: "được nấu, được nướng" },
    { kanji: "焼く", kana: "やく", meaning: "nướng, nấu" },
    { kanji: "ゆでる", kana: "ゆでる", meaning: "luộc" },
    { kanji: "揚げる", kana: "あげる", meaning: "rán ngập" },
    { kanji: "蒸す", kana: "むす", meaning: "hấp" }
  ]
};
