export const lesson8Data = {
  title: "Bài 8: Phó từ (45 từ)",
  japanese: "第8課: 副詞",
  words: [
    { kanji: "非常に", kana: "ひじょうに", meaning: "rất" },
    { kanji: "大変に", kana: "たいへんに", meaning: "khủng khiếp, rất nhiều" },
    { kanji: "ほとんど", kana: "ほとんど", meaning: "gần như hoàn toàn" },
    { kanji: "大体", kana: "だいたい", meaning: "phần lớn, trong khoảng" },
    { kanji: "かなり", kana: "かなり", meaning: "khá" },
    { kanji: "ずいぶん", kana: "ずいぶん", meaning: "đáng kể" },
    { kanji: "けっこう", kana: "けっこう", meaning: "rất" },
    { kanji: "大分", kana: "だいぶ", meaning: "chủ yếu, khá" },
    { kanji: "もっと", kana: "もっと", meaning: "hơn, nữa" },
    { kanji: "しっかり", kana: "しっかり", meaning: "toàn bộ, chắc chắn" },
    { kanji: "いっぱい", kana: "いっぱい", meaning: "đầy" },
    { kanji: "ぎりぎり", kana: "ぎりぎり", meaning: "gần, sát nút" },
    { kanji: "ぴったり", kana: "ぴったり", meaning: "vừa vặn, đúng" },
    { kanji: "たいてい", kana: "たいてい", meaning: "đại thể, thường" },
    { kanji: "同時に", kana: "どうじに", meaning: "cùng lúc" },
    { kanji: "前もって", kana: "まえもって", meaning: "trước" },
    { kanji: "すぐに", kana: "すぐに", meaning: "ngay lập tức" },
    { kanji: "もうすぐ", kana: "もうすぐ", meaning: "sắp" },
    { kanji: "突然", kana: "とつぜん", meaning: "đột nhiên" },
    { kanji: "あっという間に", kana: "あっというまに", meaning: "loáng một cái" },
    { kanji: "いつの間にか", kana: "いつのまにか", meaning: "lúc nào không biết" },
    { kanji: "しばらく", kana: "しばらく", meaning: "một chút, một thời gian" },
    { kanji: "ずっと", kana: "ずっと", meaning: "suốt, nhiều" },
    { kanji: "相変わらず", kana: "あいかわらず", meaning: "như mọi khi" },
    { kanji: "次々に", kana: "つぎつぎに", meaning: "lần lượt" },
    { kanji: "どんどん", kana: "どんどん", meaning: "dần dần, nhanh chóng" },
    { kanji: "ますます", kana: "ますます", meaning: "càng ngày càng" },
    { kanji: "やっと", kana: "やっと", meaning: "cuối cùng, vừa đủ" },
    { kanji: "とうとう", kana: "とうとう", meaning: "sau cùng, cuối cùng, sau tất cả" },
    { kanji: "ついに", kana: "ついに", meaning: "cuối cùng, sau cùng" },
    { kanji: "もちろん", kana: "もちろん", meaning: "tất nhiên" },
    { kanji: "やはり", kana: "やはり", meaning: "như dự tính" },
    { kanji: "きっと", kana: "きっと", meaning: "nhất định" },
    { kanji: "ぜひ", kana: "ぜひ", meaning: "bằng mọi giá, rất (muốn)" },
    { kanji: "なるべく", kana: "なるべく", meaning: "càng nhiều càng tốt" },
    { kanji: "案外", kana: "あんがい", meaning: "không ngờ đến" },
    { kanji: "もしかすると", kana: "もしかすると", accepts: ["もしかしたら", "もしかして"], meaning: "có lẽ" },
    { kanji: "まさか", kana: "まさか", meaning: "không thể ngờ, không" },
    { kanji: "うっかり", kana: "うっかり", meaning: "ngơ ngác, không để ý" },
    { kanji: "つい", kana: "つい", meaning: "vô ý, buột" },
    { kanji: "思わず", kana: "おもわず", meaning: "không ngờ đến" },
    { kanji: "ほっと", kana: "ほっと", meaning: "yên tâm" },
    { kanji: "いらいら", kana: "いらいら", meaning: "khó chịu, nóng giận" },
    { kanji: "のんびり", kana: "のんびり", meaning: "tận hưởng, thong thả" },
    { kanji: "実は", kana: "じつは", meaning: "thực tế là" }
  ]
};
