export const lesson6Data = {
  title: "Bài 6: Katakana (40 từ)",
  japanese: "第6課: カタカナ",
  words: [
    { kanji: "クラスメート", kana: "クラスメート", meaning: "bạn cùng lớp" },
    { kanji: "グループ", kana: "グループ", meaning: "nhóm" },
    { kanji: "チーム", kana: "チーム", meaning: "đội" },
    { kanji: "プロフェッショナル", kana: "プロフェッショナル", meaning: "chuyên nghiệp" },
    { kanji: "アマチュア", kana: "アマチュア", meaning: "nghiệp dư" },
    { kanji: "トレーニング", kana: "トレーニング", meaning: "đào tạo" },
    { kanji: "マッサージ", kana: "マッサージ", meaning: "mát xa" },
    { kanji: "アドバイス", kana: "アドバイス", meaning: "khuyên" },
    { kanji: "アイデア", kana: "アイデア", accepts: ["アイディア"], meaning: "ý tưởng" },
    { kanji: "トップ", kana: "トップ", meaning: "top" },
    { kanji: "スピード", kana: "スピード", meaning: "tốc độ" },
    { kanji: "ラッシュ", kana: "ラッシュ", meaning: "đông đúc" },
    { kanji: "バイク", kana: "バイク", meaning: "xe máy" },
    { kanji: "ヘルメット", kana: "ヘルメット", meaning: "mũ bảo hiểm" },
    { kanji: "コンタクトレンズ", kana: "コンタクトレンズ", meaning: "kính áp tròng" },
    { kanji: "ガラス", kana: "ガラス", meaning: "kính" },
    { kanji: "プラスチック", kana: "プラスチック", meaning: "nhựa" },
    { kanji: "ベランダ", kana: "ベランダ", meaning: "ban công" },
    { kanji: "ペット", kana: "ペット", meaning: "thú cưng" },
    { kanji: "ベンチ", kana: "ベンチ", meaning: "ghế bành" },
    { kanji: "デザイン", kana: "デザイン", meaning: "thiết kế" },
    { kanji: "バーゲンセール", kana: "バーゲンセール", meaning: "sale" },
    { kanji: "パート", kana: "パート", meaning: "làm thêm" },
    { kanji: "コンビニエンスストア", kana: "コンビニエンスストア", meaning: "cửa hàng tiện ích" },
    { kanji: "レジ", kana: "レジ", meaning: "máy tính tiền" },
    { kanji: "レシート", kana: "レシート", meaning: "hóa đơn" },
    { kanji: "インスタント", kana: "インスタント", meaning: "ăn liền" },
    { kanji: "ファストフード", kana: "ファストフード", meaning: "đồ ăn nhanh" },
    { kanji: "フルーツ", kana: "フルーツ", meaning: "trái cây" },
    { kanji: "デザート", kana: "デザート", meaning: "tráng miệng" },
    { kanji: "インターネット", kana: "インターネット", meaning: "internet" },
    { kanji: "チャイム", kana: "チャイム", meaning: "chuông" },
    { kanji: "アナウンス", kana: "アナウンス", meaning: "thông báo" },
    { kanji: "メッセージ", kana: "メッセージ", meaning: "tin nhắn" },
    { kanji: "パンフレット", kana: "パンフレット", meaning: "tờ rơi" },
    { kanji: "カード", kana: "カード", meaning: "card" },
    { kanji: "インタビュー", kana: "インタビュー", meaning: "phỏng vấn" },
    { kanji: "アンケート", kana: "アンケート", meaning: "tờ câu hỏi" },
    { kanji: "データ", kana: "データ", meaning: "dữ liệu" },
    { kanji: "パーセント", kana: "パーセント", meaning: "phần trăm" }
  ]
};
