export const lesson4Data = {
  title: "Bài 4: Động từ & Danh từ (111 từ)",
  japanese: "第4課: 動詞 & 名詞",
  words: [
    { kanji: "温まる", kana: "あたたまる", meaning: "trở nên ấm hơn" },
    { kanji: "温める", kana: "あたためる", meaning: "làm ấm, làm nóng" },
    { kanji: "高まる", kana: "たかまる", meaning: "cao lên" },
    { kanji: "高める", kana: "たかめる", meaning: "làm cao lên" },
    { kanji: "強まる", kana: "つよまる", meaning: "mạnh lên" },
    { kanji: "強める", kana: "つよめる", meaning: "làm mạnh lên" },
    { kanji: "弱まる", kana: "よわまる", meaning: "yếu đi" },
    { kanji: "弱める", kana: "よわめる", meaning: "làm yếu đi" },
    { kanji: "広まる", kana: "ひろまる", meaning: "rộng ra" },
    { kanji: "広める", kana: "ひろめる", meaning: "làm rộng ra" },
    { kanji: "深まる", kana: "ふかまる", meaning: "sâu hơn" },
    { kanji: "深める", kana: "ふかめる", meaning: "làm sâu thêm" },
    { kanji: "世話", kana: "せわ", meaning: "chăm sóc" },
    { kanji: "家庭", kana: "かてい", meaning: "gia đình" },
    { kanji: "協力", kana: "きょうりょく", meaning: "hiệp lực" },
    { kanji: "感謝", kana: "かんしゃ", meaning: "cảm tạ" },
    { kanji: "お礼", kana: "おれい", meaning: "đáp lễ" },
    { kanji: "お詫び", kana: "おわび", meaning: "xin lỗi" },
    { kanji: "おじぎ", kana: "おじぎ", meaning: "cúi chào" },
    { kanji: "握手", kana: "あくしゅ", meaning: "bắt tay" },
    { kanji: "いじわる", kana: "いじわる", meaning: "xấu bụng" },
    { kanji: "いたずら", kana: "いたずら", meaning: "nghịch ngợm" },
    { kanji: "節約", kana: "せつやく", meaning: "tiết kiệm" },
    { kanji: "経営", kana: "けいえい", meaning: "quản lý" },
    { kanji: "反省", kana: "はんせい", meaning: "tự kiểm tra" },
    { kanji: "実行", kana: "じっこう", meaning: "thực hành" },
    { kanji: "進歩", kana: "しんぽ", meaning: "tiến bộ" },
    { kanji: "変化", kana: "へんか", meaning: "thay đổi, biến hóa" },
    { kanji: "発達", kana: "はったつ", meaning: "phát triển" },
    { kanji: "体力", kana: "たいりょく", meaning: "thể lực" },
    { kanji: "出場", kana: "しゅつじょう", meaning: "tham dự" },
    { kanji: "活躍", kana: "かつやく", meaning: "hoạt động" },
    { kanji: "競争", kana: "きょうそう", meaning: "cạnh tranh" },
    { kanji: "応援", kana: "おうえん", meaning: "cổ vũ" },
    { kanji: "拍手", kana: "はくしゅ", meaning: "vỗ tay" },
    { kanji: "人気", kana: "にんき", meaning: "nổi tiếng" },
    { kanji: "うわさ", kana: "うわさ", meaning: "tin đồn" },
    { kanji: "情報", kana: "じょうほう", meaning: "thông tin" },
    { kanji: "交換", kana: "こうかん", meaning: "trao đổi" },
    { kanji: "流行", kana: "りゅうこう", meaning: "trào lưu" },
    { kanji: "宣伝", kana: "せんでん", meaning: "tuyên truyền" },
    { kanji: "広告", kana: "こうこく", meaning: "quảng cáo" },
    { kanji: "注目", kana: "ちゅうmoku", meaning: "chú trọng" },
    { kanji: "通訳", kana: "つうやく", meaning: "thông dịch" },
    { kanji: "翻訳", kana: "ほんやく", meaning: "biên dịch" },
    { kanji: "伝言", kana: "でんごん", meaning: "tin nhắn thoại" },
    { kanji: "報告", kana: "ほうこく", meaning: "báo cáo" },
    { kanji: "録画", kana: "ろくが", meaning: "ghi lại" },
    { kanji: "混雑", kana: "こんざつ", meaning: "hỗn tạp" },
    { kanji: "渋滞", kana: "じゅうたい", meaning: "tắc đường" },
    { kanji: "衝突", kana: "しょうとつ", meaning: "xung đột" },
    { kanji: "被害", kana: "ひがい", meaning: "thiệt hại" },
    { kanji: "事故", kana: "じこ", meaning: "tai nạn" },
    { kanji: "事件", kana: "じけん", meaning: "sự kiện" },
    { kanji: "故障", kana: "こしょう", meaning: "hỏng" },
    { kanji: "修理", kana: "しゅうり", meaning: "sửa chữa" },
    { kanji: "停電", kana: "ていでん", meaning: "mất điện" },
    { kanji: "調子", kana: "ちょうし", meaning: "trạng thái" },
    { kanji: "緊張", kana: "きんちょう", meaning: "lo lắng" },
    { kanji: "自身", kana: "じしん", meaning: "tự tin" },
    { kanji: "自慢", kana: "じまん", meaning: "tự mãn" },
    { kanji: "感心", kana: "かんしん", meaning: "quan tâm" },
    { kanji: "感動", kana: "かんどう", meaning: "cảm động" },
    { kanji: "興奮", kana: "こうふん", meaning: "hưng phấn" },
    { kanji: "感想", kana: "かんそう", meaning: "cảm tưởng" },
    { kanji: "予想", kana: "よそう", meaning: "dự đoán" },
    { kanji: "専門", kana: "せんもん", meaning: "chuyên môn" },
    { kanji: "研究", kana: "けんきゅう", meaning: "nghiên cứu" },
    { kanji: "調査", kana: "ちょうさ", meaning: "điều tra" },
    { kanji: "原因", kana: "げんいん", meaning: "nguyên nhân" },
    { kanji: "結果", kana: "けっか", meaning: "kết quả" },
    { kanji: "解決", kana: "かいけつ", meaning: "giải quyết" },
    { kanji: "確認", kana: "かくにん", meaning: "xác nhận" },
    { kanji: "利用", kana: "りよう", meaning: "sử dụng" },
    { kanji: "理解", kana: "りかい", meaning: "lý giải" },
    { kanji: "発見", kana: "はっけん", meaning: "phát kiến" },
    { kanji: "発明", kana: "はつめい", meaning: "phát minh" },
    { kanji: "関係", kana: "かんけい", meaning: "quan hệ" },
    { kanji: "団体", kana: "だんたい", meaning: "đoàn thể" },
    { kanji: "選挙", kana: "せんきょ", meaning: "bầu cử" },
    { kanji: "税金", kana: "ぜいきん", meaning: "thuế" },
    { kanji: "責任", kana: "せきにん", meaning: "trách nhiệm" },
    { kanji: "書類", kana: "しょるい", meaning: "tài liệu" },
    { kanji: "題名", kana: "だいめい", meaning: "tiêu đề" },
    { kanji: "条件", kana: "じょうけん", meaning: "điều kiện" },
    { kanji: "締め切り", kana: "しめきり", meaning: "hạn cuối" },
    { kanji: "期間", kana: "きかん", meaning: "thời gian, thời kỳ" },
    { kanji: "倍", kana: "ばい", meaning: "lần" },
    { kanji: "くじ", kana: "くじ", meaning: "xổ số, rút thăm" },
    { kanji: "近道", kana: "ちかみち", meaning: "đường tắt" },
    { kanji: "中心", kana: "ちゅうしん", meaning: "trung tâm" },
    { kanji: "辺り", kana: "あたり", meaning: "gần, lân cận" },
    { kanji: "周り", kana: "まわり", meaning: "xung quanh, vòng quanh" },
    { kanji: "穴", kana: "あな", meaning: "lỗ" },
    { kanji: "列", kana: "れつ", meaning: "hàng" },
    { kanji: "幅", kana: "はば", meaning: "chiều rộng" },
    { kanji: "範囲", kana: "はんい", meaning: "phạm vi" },
    { kanji: "内容", kana: "ないよう", meaning: "nội dung" },
    { kanji: "中身", kana: "なかみ", meaning: "bên trong" },
    { kanji: "特徴", kana: "とくちょう", meaning: "đặc trưng" },
    { kanji: "普通", kana: "ふつう", meaning: "bình thường" },
    { kanji: "当たり前", kana: "あたりまえ", meaning: "đương nhiên" },
    { kanji: "偽", kana: "にせ", meaning: "giả" },
    { kanji: "別", kana: "べつ", meaning: "khác" },
    { kanji: "国籍", kana: "こくせき", meaning: "quốc tịch" },
    { kanji: "東洋", kana: "とうよう", meaning: "phương đông" },
    { kanji: "西洋", kana: "せいよう", meaning: "phương tây" },
    { kanji: "国際", kana: "こくさい", meaning: "quốc tế" },
    { kanji: "自然", kana: "しぜん", meaning: "tự nhiên" },
    { kanji: "景色", kana: "けしき", meaning: "phong cảnh" },
    { kanji: "宗教", kana: "しゅうきょう", meaning: "tôn giáo" },
    { kanji: "愛", kana: "あい", meaning: "yêu" }
  ]
};
