export const lesson5Data = {
  title: "Bài 5: Động từ B (99 từ)",
  japanese: "第5課: 動詞Ｂ",
  words: [
    { kanji: "届く", kana: "とどく", meaning: "được giao đến" },
    { kanji: "届ける", kana: "とどける", meaning: "giao đến" },
    { kanji: "かく", kana: "かく", meaning: "gãi" },
    { kanji: "つかむ", kana: "つかむ", meaning: "tóm, chộp" },
    { kanji: "握る", kana: "にぎる", meaning: "nắm chặt" },
    { kanji: "抑える", kana: "おさえる", meaning: "giữ, kiềm chế" },
    { kanji: "近づく", kana: "ちかづく", meaning: "lại gần" },
    { kanji: "近づける", kana: "ちかづける", meaning: "mang đến gần" },
    { kanji: "合う", kana: "あう", meaning: "gặp, vừa vặn, hợp" },
    { kanji: "合わせる", kana: "あわせる", meaning: "tập hợp, hiệp lực" },
    { kanji: "当たる", kana: "あたる", meaning: "bị đánh, trúng (số)" },
    { kanji: "あてる", kana: "あてる", meaning: "đánh, đặt vào" },
    { kanji: "比べる", kana: "くらべる", meaning: "so sánh" },
    { kanji: "似合う", kana: "にあう", meaning: "hợp (quần áo...)" },
    { kanji: "似る", kana: "にる", meaning: "giống" },
    { kanji: "似せる", kana: "にせる", meaning: "bắt chước" },
    { kanji: "分かれる", kana: "わかれる", meaning: "được chia ra" },
    { kanji: "分ける", kana: "わける", meaning: "chia" },
    { kanji: "足す", kana: "たす", meaning: "cộng, thêm vào" },
    { kanji: "引く", kana: "ひく", meaning: "kéo, trừ" },
    { kanji: "増える", kana: "ふえる", meaning: "tăng lên" },
    { kanji: "増やす", kana: "ふやす", meaning: "làm tăng lên" },
    { kanji: "減る", kana: "へる", meaning: "giảm xuống" },
    { kanji: "減らす", kana: "へらす", meaning: "làm giảm xuống" },
    { kanji: "変わる", kana: "かわる", meaning: "thay đổi" },
    { kanji: "変える", kana: "かえる", meaning: "làm thay đổi" },
    { kanji: "代わる・替わる・換わる", kana: "かわる", meaning: "thay, thế chỗ" },
    { kanji: "代える・替える・換える", kana: "かえる", meaning: "đổi, thay đổi" },
    { kanji: "返る", kana: "かえる", meaning: "được trả lại" },
    { kanji: "返す", kana: "かえす", meaning: "trả lại" },
    { kanji: "譲る", kana: "ゆずる", meaning: "nhường" },
    { kanji: "助かる", kana: "たすかる", meaning: "được giúp, may mắn thoát nạn" },
    { kanji: "助ける", kana: "たすける", meaning: "giúp" },
    { kanji: "いじめる", kana: "いじめる", meaning: "bắt nạt" },
    { kanji: "だます", kana: "だます", meaning: "lừa gạt" },
    { kanji: "盗む", kana: "ぬすむ", meaning: "lấy cắp" },
    { kanji: "刺さる", kana: "ささる", meaning: "bị đâm, bị châm" },
    { kanji: "刺す", kana: "さす", meaning: "đâm, châm" },
    { kanji: "殺す", kana: "ころす", meaning: "giết" },
    { kanji: "隠れる", kana: "かくれる", meaning: "ẩn náu, trốn" },
    { kanji: "隠す", kana: "かくす", meaning: "che giấu" },
    { kanji: "埋まる", kana: "うまる", meaning: "bị chôn" },
    { kanji: "埋める", kana: "うめる", meaning: "chôn cất, lấp đầy" },
    { kanji: "囲む", kana: "かこむ", meaning: "vây quanh" },
    { kanji: "詰まる", kana: "つまる", meaning: "đầy, chặt, nghẹt" },
    { kanji: "詰める", kana: "つめる", meaning: "đóng gói, lấp kín" },
    { kanji: "開く", kana: "ひらく", meaning: "mở" },
    { kanji: "閉じる", kana: "とじる", meaning: "đóng" },
    { kanji: "飛ぶ", kana: "とぶ", meaning: "bay" },
    { kanji: "飛ばす", kana: "とばす", meaning: "cho bay, bỏ qua" },
    { kanji: "振る", kana: "ふる", meaning: "rung, vẫy" },
    { kanji: "めくる", kana: "めくる", meaning: "lật lên (trang sách...)" },
    { kanji: "見かける", kana: "みかける", meaning: "tình cờ thấy" },
    { kanji: "確かめる", kana: "たしかめる", meaning: "kiểm tra lại" },
    { kanji: "試す", kana: "ためす", meaning: "thử" },
    { kanji: "繰り返す", kana: "くりかえす", meaning: "lặp lại" },
    { kanji: "訳す", kana: "やくす", meaning: "dịch" },
    { kanji: "行う", kana: "おこなう", meaning: "tổ chức, thực hiện" },
    { kanji: "間違う", kana: "まちがう", meaning: "bị sai" },
    { kanji: "間違える", kana: "まちがえる", meaning: "làm sai" },
    { kanji: "許す", kana: "ゆるす", meaning: "tha thứ, cho phép" },
    { kanji: "慣れる", kana: "なれる", meaning: "quen với" },
    { kanji: "慣らす", kana: "ならす", meaning: "làm cho quen, khởi động" },
    { kanji: "立つ", kana: "たつ", meaning: "đứng" },
    { kanji: "立てる", kana: "たてる", meaning: "dựng lên" },
    { kanji: "建つ", kana: "たつ", meaning: "được xây dựng" },
    { kanji: "建てる", kana: "たてる", meaning: "xây" },
    { kanji: "育つ", kana: "そだつ", meaning: "được nuôi dạy" },
    { kanji: "育てる", kana: "そだてる", meaning: "nuôi dạy" },
    { kanji: "生える", kana: "はえる", meaning: "mọc (tóc, răng, cỏ...)" },
    { kanji: "生やす", kana: "はやす", meaning: "nuôi (râu)" },
    { kanji: "汚れる", kana: "よごれる", meaning: "bị bẩn" },
    { kanji: "汚す", kana: "よごす", meaning: "làm bẩn" },
    { kanji: "壊れる", kana: "こわれる", meaning: "bị hỏng" },
    { kanji: "壊す", kana: "こわす", meaning: "làm hỏng" },
    { kanji: "割れる", kana: "われる", meaning: "bị vỡ" },
    { kanji: "割る", kana: "わる", meaning: "làm vỡ" },
    { kanji: "折れる", kana: "おれる", meaning: "bị gãy" },
    { kanji: "折る", kana: "おる", meaning: "làm gãy" },
    { kanji: "破れる", kana: "やぶれる", meaning: "bị rách" },
    { kanji: "破る", kana: "やぶる", meaning: "xé rách, phá vỡ (kỷ lục...)" },
    { kanji: "曲がる", kana: "まがる", meaning: "gập, cong, rẽ" },
    { kanji: "曲げる", kana: "まげる", meaning: "bẻ, uốn" },
    { kanji: "外れる", kana: "はずれる", meaning: "bị rời ra, tuột ra" },
    { kanji: "外す", kana: "はずす", meaning: "tách ra, tháo ra" },
    { kanji: "揺れる", kana: "ゆれる", meaning: "bị rung, dao động" },
    { kanji: "揺らす", kana: "ゆらす", meaning: "đung đưa, làm rung" },
    { kanji: "流れる", kana: "ながれる", meaning: "chảy" },
    { kanji: "流す", kana: "ながす", meaning: "cho chảy, xả nước" },
    { kanji: "濡れる", kana: "ぬれる", meaning: "bị ướt" },
    { kanji: "濡らす", kana: "ぬらす", meaning: "làm ướt" },
    { kanji: "迷う", kana: "まよう", meaning: "lạc đường, phân vân" },
    { kanji: "悩む", kana: "なやむ", meaning: "băn khoăn, đau đầu" },
    { kanji: "慌てる", kana: "あわてる", meaning: "vội vàng, cuốn cuồng" },
    { kanji: "覚める", kana: "さめる", meaning: "thức dậy, tỉnh ngộ" },
    { kanji: "覚ます", kana: "さます", meaning: "mở mắt, thức tỉnh" },
    { kanji: "眠る", kana: "ねむる", meaning: "ngủ" },
    { kanji: "祈る", kana: "いのる", meaning: "cầu nguyện, khấn" },
    { kanji: "祝う", kana: "いわう", meaning: "ăn mừng, chúc mừng" },
    { kanji: "感じる", kana: "かんじる", meaning: "cảm thấy" }
  ]
};
