export const lesson3Data = {
  title: "Bài 3: Liên từ & Tính từ (77 từ)",
  japanese: "第3課: 連用名詞 & 形容詞",
  words: [
    { kanji: "飾り", kana: "かざり", meaning: "trang trí" },
    { kanji: "遊び", kana: "あそび", meaning: "chơi" },
    { kanji: "集まり", kana: "あつまり", meaning: "tập hợp" },
    { kanji: "教え", kana: "おしえ", meaning: "dạy" },
    { kanji: "踊り", kana: "おどり", meaning: "nhảy" },
    { kanji: "思い", kana: "おもい", meaning: "suy nghĩ, cảm giác" },
    { kanji: "考え", kana: "かんがえ", meaning: "nghĩ, ý tưởng" },
    { kanji: "片づけ", kana: "かたづけ", meaning: "ngăn nắp, dọn dẹp" },
    { kanji: "手伝い", kana: "てつだい", meaning: "giúp đỡ" },
    { kanji: "働き", kana: "はたらき", meaning: "hoạt động, chức năng" },
    { kanji: "決まり", kana: "きまり", meaning: "luật lệ, quy định" },
    { kanji: "騒ぎ", kana: "さわぎ", meaning: "ồn ào, om xòm" },
    { kanji: "知らせ", kana: "しらせ", meaning: "tin tức, thông báo" },
    { kanji: "頼み", kana: "たのみ", meaning: "yêu cầu, nhờ vả" },
    { kanji: "疲れ", kana: "つかれ", meaning: "vất vả, mệt mỏi" },
    { kanji: "違い", kana: "ちがい", meaning: "khác biệt" },
    { kanji: "始め", kana: "はじめ", meaning: "khởi đầu" },
    { kanji: "続き", kana: "つづき", meaning: "tiếp tục, diễn biến" },
    { kanji: "暮れ", kana: "くれ", meaning: "cuối năm, chiều tối" },
    { kanji: "行き", kana: "いき", meaning: "đi" },
    { kanji: "帰り", kana: "かえり", meaning: "trở về" },
    { kanji: "急ぎ", kana: "いそぎ", meaning: "khẩn cấp, vội vã" },
    { kanji: "遅れ", kana: "おくれ", meaning: "gián đoạn, trễ" },
    { kanji: "貸し", kana: "かし", meaning: "cho mượn" },
    { kanji: "借り", kana: "かり", meaning: "mượn" },
    { kanji: "勝ち", kana: "かち", meaning: "thắng" },
    { kanji: "負け", kana: "まけ", meaning: "thua" },
    { kanji: "迎え", kana: "むかえ", meaning: "đón" },
    { kanji: "始まり", kana: "はじまり", meaning: "bắt đầu" },
    { kanji: "終わり", kana: "おわり", meaning: "kết thúc" },
    { kanji: "戻り", kana: "もどり", meaning: "trở về, trả lại" },
    { kanji: "別れ", kana: "わかれ", meaning: "chia ly" },
    { kanji: "喜び", kana: "よろこび", meaning: "hớn hở, niềm vui" },
    { kanji: "楽しみ", kana: "たのしみ", meaning: "sung sướng, sự mong đợi" },
    { kanji: "笑い", kana: "わらい", meaning: "tiếng cười" },
    { kanji: "驚き", kana: "おどろき", meaning: "sự ngạc nhiên" },
    { kanji: "怒り", kana: "いかり", meaning: "sự giận dữ" },
    { kanji: "悲しみ", kana: "かなしみ", meaning: "sự buồn bã" },
    { kanji: "幸せな", kana: "しあわせな", meaning: "hạnh phúc" },
    { kanji: "得意な", kana: "とくいな", meaning: "mạnh, giỏi" },
    { kanji: "苦手な", kana: "にがてな", meaning: "yếu, kém" },
    { kanji: "熱心な", kana: "ねっしんな", meaning: "chăm chỉ, nhiệt tình" },
    { kanji: "夢中な", kana: "むちゅうな", meaning: "chú tâm, say mê" },
    { kanji: "退屈な", kana: "たいくつな", meaning: "chán ngắt, buồn tẻ" },
    { kanji: "健康な", kana: "けんこうな", meaning: "khỏe khoắn, lành mạnh" },
    { kanji: "苦しい", kana: "くるしい", meaning: "khổ cực, đau đớn" },
    { kanji: "平気な", kana: "へいきな", meaning: "bình thản, thản nhiên" },
    { kanji: "悔しい", kana: "くやしい", meaning: "cay cú, đáng tiếc" },
    { kanji: "うらやましい", kana: "うらやましい", meaning: "ghen tỵ, ngưỡng mộ" },
    { kanji: "かゆい", kana: "かゆい", meaning: "ngứa" },
    { kanji: "おとなしい", kana: "おとなしい", meaning: "trầm lặng, hiền lành" },
    { kanji: "我慢強い", kana: "がまんづよい", meaning: "chịu đựng giỏi" },
    { kanji: "正直な", kana: "しょうじきな", meaning: "trung thực, chân thật" },
    { kanji: "けちな", kana: "けちな", meaning: "kẹt xỉ, keo kiệt" },
    { kanji: "我儘な", kana: "わがままな", meaning: "ích kỷ" },
    { kanji: "積極的な", kana: "せっきょくてきな", meaning: "tích cực" },
    { kanji: "消極的な", kana: "しょうきょくてきな", meaning: "tiêu cực" },
    { kanji: "満足な", kana: "まんぞくな", meaning: "thỏa mãn, hài lòng" },
    { kanji: "不満な", kana: "ふまんな", meaning: "bất mãn" },
    { kanji: "不安な", kana: "ふあんな", meaning: "bất an" },
    { kanji: "大変な", kana: "たいheんな", meaning: "tồi tệ, vất vả" },
    { kanji: "無理な", kana: "むりな", meaning: "vô lý, quá sức" },
    { kanji: "不注意な", kana: "ふちゅういな", meaning: "không chú ý, lơ đễnh" },
    { kanji: "楽な", kana: "らくな", meaning: "thoải mái, nhàn hạ" },
    { kanji: "面倒な", kana: "めんどうな", meaning: "phiền phức" },
    { kanji: "失礼な", kana: "しつれいな", meaning: "thất lễ" },
    { kanji: "当然な", kana: "とうぜんな", meaning: "đương nhiên, tất nhiên" },
    { kanji: "意外な", kana: "いがいな", meaning: "không ngờ đến" },
    { kanji: "結構な", kana: "けっこうな", meaning: "tốt, đủ" },
    { kanji: "派手な", kana: "はでな", meaning: "lòe loẹt, sặc sỡ" },
    { kanji: "地味な", kana: "じみな", meaning: "giản dị, đơn sơ" },
    { kanji: "おしゃれな", kana: "おしゃれな", meaning: "thời trang, phong cách" },
    { kanji: "変な", kana: "へんな", meaning: "lạ, kỳ quặc" },
    { kanji: "不思議な", kana: "ふしぎな", meaning: "thần bí, kỳ quái" },
    { kanji: "ましな", kana: "ましな", meaning: "khá hơn, tốt lên" },
    { kanji: "むだな", kana: "むだな", meaning: "lãng phí, vô ích" },
    { kanji: "自由な", kana: "じゆうな", meaning: "tự do" },
    { kanji: "不自由な", kana: "ふじゆうな", meaning: "tàn tật, không tự do" }
  ]
};
